"""
db.py — the run index.

The database is an **index, not the truth**. Every row here is derived from a
file under the run root, and :func:`rebuild` must be able to reconstruct the
whole database from those files alone. Nothing in the driver may read state that
exists only in the database or only in RAM.

On-disk layout, which is the authority::

    <run_root>/
        driver.db                     <- this database; disposable
        <run_key>/
            run.json                  <- run metadata, written once at init
            turns/0001.json           <- one record per turn, written at record time
            scripts/                  <- scripts generated by ms_modify
            logs/                     <- executor stdout/stderr

A turn record is written to ``turns/NNNN.json`` *before* the corresponding rows
are inserted. If the process dies between the two, ``rebuild`` recovers the turn.
If it dies before the file is written, the turn did not happen.

SQLite is chosen for having no server. Keep the run root on local disk: SQLite
file locking over NFS is unreliable. All SQL lives in this module and the DDL is
kept ANSI-portable, so moving to Postgres is a DDL rewrite and a placeholder
change rather than a redesign. The two known non-portable points are marked
``PORTABILITY``.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from collections.abc import Iterator
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# --------------------------------------------------------------------------
# Vocabulary
# --------------------------------------------------------------------------

#: Terminal and non-terminal states a run may be in.
RUN_STATUS = ("active", "done", "failed", "needs_human")

#: What became of a turn. ``accepted`` is the one that counted for its stage;
#: at most one accepted turn exists per (run, stage).
TURN_OUTCOME = ("pending", "accepted", "retried", "failed")

#: Executor-reported job states. Mirrors the executor protocol.
JOB_STATE = ("pending", "running", "done", "failed")

#: Artifact kinds. Free-form enough to extend without a migration.
ARTIFACT_KIND = ("caltable", "ms", "image", "script", "plot", "log", "other")


# --------------------------------------------------------------------------
# Layout
# --------------------------------------------------------------------------


def db_path(run_root: Path | str) -> Path:
    return Path(run_root) / "driver.db"


def run_dir(run_root: Path | str, run_key: str) -> Path:
    return Path(run_root) / run_key


def run_json_path(run_root: Path | str, run_key: str) -> Path:
    return run_dir(run_root, run_key) / "run.json"


def turns_dir(run_root: Path | str, run_key: str) -> Path:
    return run_dir(run_root, run_key) / "turns"


def turn_json_path(run_root: Path | str, run_key: str, ordinal: int) -> Path:
    return turns_dir(run_root, run_key) / f"{ordinal:04d}.json"


def scripts_dir(run_root: Path | str, run_key: str) -> Path:
    return run_dir(run_root, run_key) / "scripts"


def logs_dir(run_root: Path | str, run_key: str) -> Path:
    return run_dir(run_root, run_key) / "logs"


def ensure_run_dirs(run_root: Path | str, run_key: str) -> Path:
    """Create the directory tree for one run and return its root."""
    d = run_dir(run_root, run_key)
    for sub in (turns_dir, scripts_dir, logs_dir):
        sub(run_root, run_key).mkdir(parents=True, exist_ok=True)
    return d


# --------------------------------------------------------------------------
# Identity
# --------------------------------------------------------------------------


def utc_now() -> str:
    """Current time as an ISO-8601 UTC string, second resolution.

    Timestamps are stored as TEXT so they are portable and sort lexically.
    """
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def make_run_key(ms_path: Path | str, started_at: str | None = None) -> str:
    """Build a sortable, readable, unique key for a run.

    ``20260827T142530Z-3c286_b6-a91f`` — compact timestamp, MS name, and a short
    hash of the absolute MS path. The timestamp makes it sort chronologically;
    the hash disambiguates two runs started in the same second on different
    copies of a similarly-named MS.
    """
    started_at = started_at or utc_now()
    stamp = started_at.replace("-", "").replace(":", "")
    name = Path(ms_path).name
    for suffix in (".ms", ".MS"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
    slug = "".join(c if c.isalnum() else "_" for c in name).strip("_").lower()[:32] or "ms"
    digest = hashlib.sha256(str(Path(ms_path).absolute()).encode()).hexdigest()[:4]
    return f"{stamp}-{slug}-{digest}"


def checksum_path(path: Path | str, *, chunk: int = 1 << 20) -> str:
    """Content hash of a file, or of a directory tree such as a CASA caltable.

    CASA products are directories, so a plain file hash will not do. For a
    directory the hash covers each contained file's run-root-relative path and
    its bytes, walked in sorted order, so the result is stable across machines.

    Returns ``""`` if the path does not exist — an absent artifact is recorded
    as absent rather than raising, because a failed job legitimately produces
    nothing.
    """
    p = Path(path)
    if not p.exists():
        return ""
    h = hashlib.sha256()
    if p.is_file():
        _hash_file(h, p, chunk)
        return h.hexdigest()
    for f in sorted(x for x in p.rglob("*") if x.is_file()):
        h.update(str(f.relative_to(p)).encode())
        _hash_file(h, f, chunk)
    return h.hexdigest()


def _hash_file(h: Any, path: Path, chunk: int) -> None:
    with path.open("rb") as fh:
        while block := fh.read(chunk):
            h.update(block)


def path_size(path: Path | str) -> int:
    """Total bytes at a path, recursing into directories. 0 if absent."""
    p = Path(path)
    if not p.exists():
        return 0
    if p.is_file():
        return p.stat().st_size
    return sum(f.stat().st_size for f in p.rglob("*") if f.is_file())


def path_mtime(path: Path | str) -> str:
    """Modification time as an ISO-8601 UTC string. Empty string if absent."""
    p = Path(path)
    if not p.exists():
        return ""
    return datetime.fromtimestamp(p.stat().st_mtime, UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


# --------------------------------------------------------------------------
# Schema
# --------------------------------------------------------------------------

# PORTABILITY: `INTEGER PRIMARY KEY` is SQLite's rowid alias. On Postgres this
# becomes `INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`. That, and the
# `?` placeholder style below, are the only two things a port must change.
SCHEMA = """
CREATE TABLE IF NOT EXISTS runs (
    id          INTEGER PRIMARY KEY,
    run_key     TEXT    NOT NULL UNIQUE,
    started_at  TEXT    NOT NULL,
    finished_at TEXT,
    ms_path     TEXT    NOT NULL,
    workdir     TEXT    NOT NULL,
    telescope   TEXT,
    backend     TEXT    NOT NULL,
    executor    TEXT    NOT NULL,
    status      TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS turns (
    id            INTEGER PRIMARY KEY,
    run_id        INTEGER NOT NULL REFERENCES runs(id),
    ordinal       INTEGER NOT NULL,
    stage         TEXT    NOT NULL,
    attempt       INTEGER NOT NULL,
    outcome       TEXT    NOT NULL,
    started_at    TEXT    NOT NULL,
    finished_at   TEXT,
    brief         TEXT,
    decision      TEXT,
    tool          TEXT,
    backend       TEXT,
    model         TEXT,
    tokens_in     INTEGER,
    tokens_out    INTEGER,
    decide_wall_s REAL,
    note          TEXT,
    UNIQUE (run_id, ordinal)
);

CREATE TABLE IF NOT EXISTS jobs (
    id           INTEGER PRIMARY KEY,
    turn_id      INTEGER NOT NULL REFERENCES turns(id),
    executor     TEXT    NOT NULL,
    handle       TEXT    NOT NULL,
    script_path  TEXT,
    state        TEXT    NOT NULL,
    submitted_at TEXT,
    finished_at  TEXT,
    exit_code    INTEGER,
    stdout_path  TEXT,
    stderr_path  TEXT
);

CREATE TABLE IF NOT EXISTS artifacts (
    id       INTEGER PRIMARY KEY,
    turn_id  INTEGER NOT NULL REFERENCES turns(id),
    path     TEXT    NOT NULL,
    kind     TEXT    NOT NULL,
    size     INTEGER,
    checksum TEXT,
    mtime    TEXT
);

CREATE TABLE IF NOT EXISTS metrics (
    id      INTEGER PRIMARY KEY,
    run_id  INTEGER NOT NULL REFERENCES runs(id),
    turn_id INTEGER REFERENCES turns(id),
    name    TEXT    NOT NULL,
    value   REAL,
    unit    TEXT
);

CREATE INDEX IF NOT EXISTS ix_turns_run    ON turns (run_id, ordinal);
CREATE INDEX IF NOT EXISTS ix_turns_stage  ON turns (run_id, stage, attempt);
CREATE INDEX IF NOT EXISTS ix_jobs_turn    ON jobs (turn_id);
CREATE INDEX IF NOT EXISTS ix_jobs_handle  ON jobs (handle);
CREATE INDEX IF NOT EXISTS ix_artifacts_turn ON artifacts (turn_id);
CREATE INDEX IF NOT EXISTS ix_metrics_name ON metrics (name);
"""


def connect(path: Path | str) -> sqlite3.Connection:
    """Open the index, creating the schema if absent.

    WAL plus a busy timeout so that two driver processes advancing different
    runs do not block each other. Write volume is a few rows per turn, so this
    is ample.
    """
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(p, timeout=30.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=30000")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(SCHEMA)
    conn.commit()
    return conn


# --------------------------------------------------------------------------
# Writes
# --------------------------------------------------------------------------


def insert_run(
    conn: sqlite3.Connection,
    *,
    run_key: str,
    ms_path: str,
    workdir: str,
    backend: str,
    executor: str,
    telescope: str | None = None,
    started_at: str | None = None,
    status: str = "active",
) -> int:
    cur = conn.execute(
        "INSERT INTO runs (run_key, started_at, ms_path, workdir, telescope,"
        " backend, executor, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        (run_key, started_at or utc_now(), ms_path, workdir, telescope, backend, executor, status),
    )
    conn.commit()
    return int(cur.lastrowid)


def set_run_status(
    conn: sqlite3.Connection, run_id: int, status: str, *, finished_at: str | None = None
) -> None:
    if status not in RUN_STATUS:
        raise ValueError(f"unknown run status {status!r}; expected one of {RUN_STATUS}")
    conn.execute(
        "UPDATE runs SET status = ?, finished_at = ? WHERE id = ?",
        (status, finished_at, run_id),
    )
    conn.commit()


def next_ordinal(conn: sqlite3.Connection, run_id: int) -> int:
    """Next turn number in a run. Monotonic; never reused, even after a failure."""
    row = conn.execute(
        "SELECT COALESCE(MAX(ordinal), 0) AS m FROM turns WHERE run_id = ?", (run_id,)
    ).fetchone()
    return int(row["m"]) + 1


def next_attempt(conn: sqlite3.Connection, run_id: int, stage: str) -> int:
    """Attempt number for the next turn at this stage. The first attempt is 1."""
    row = conn.execute(
        "SELECT COUNT(*) AS n FROM turns WHERE run_id = ? AND stage = ?", (run_id, stage)
    ).fetchone()
    return int(row["n"]) + 1


def insert_turn(
    conn: sqlite3.Connection,
    *,
    run_id: int,
    ordinal: int,
    stage: str,
    attempt: int,
    brief: str | None = None,
    decision: dict | str | None = None,
    tool: str | None = None,
    backend: str | None = None,
    model: str | None = None,
    tokens_in: int | None = None,
    tokens_out: int | None = None,
    decide_wall_s: float | None = None,
    outcome: str = "pending",
    started_at: str | None = None,
    note: str | None = None,
) -> int:
    if outcome not in TURN_OUTCOME:
        raise ValueError(f"unknown turn outcome {outcome!r}; expected one of {TURN_OUTCOME}")
    if isinstance(decision, dict):
        decision = json.dumps(decision, sort_keys=True)
    cur = conn.execute(
        "INSERT INTO turns (run_id, ordinal, stage, attempt, outcome, started_at,"
        " brief, decision, tool, backend, model, tokens_in, tokens_out,"
        " decide_wall_s, note)"
        " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            run_id,
            ordinal,
            stage,
            attempt,
            outcome,
            started_at or utc_now(),
            brief,
            decision,
            tool,
            backend,
            model,
            tokens_in,
            tokens_out,
            decide_wall_s,
            note,
        ),
    )
    conn.commit()
    return int(cur.lastrowid)


def set_turn_outcome(
    conn: sqlite3.Connection,
    turn_id: int,
    outcome: str,
    *,
    finished_at: str | None = None,
    note: str | None = None,
) -> None:
    """Close a turn.

    Marking a turn ``accepted`` demotes any previously accepted turn for the
    same (run, stage) to ``retried``, so the invariant "at most one accepted
    turn per stage" holds without the caller having to remember it.
    """
    if outcome not in TURN_OUTCOME:
        raise ValueError(f"unknown turn outcome {outcome!r}; expected one of {TURN_OUTCOME}")
    if outcome == "accepted":
        row = conn.execute("SELECT run_id, stage FROM turns WHERE id = ?", (turn_id,)).fetchone()
        if row is None:
            raise KeyError(f"no turn with id {turn_id}")
        conn.execute(
            "UPDATE turns SET outcome = 'retried'"
            " WHERE run_id = ? AND stage = ? AND outcome = 'accepted' AND id <> ?",
            (row["run_id"], row["stage"], turn_id),
        )
    conn.execute(
        "UPDATE turns SET outcome = ?, finished_at = ?, note = COALESCE(?, note) WHERE id = ?",
        (outcome, finished_at or utc_now(), note, turn_id),
    )
    conn.commit()


def insert_job(
    conn: sqlite3.Connection,
    *,
    turn_id: int,
    executor: str,
    handle: str,
    script_path: str | None = None,
    state: str = "pending",
    submitted_at: str | None = None,
    stdout_path: str | None = None,
    stderr_path: str | None = None,
) -> int:
    if state not in JOB_STATE:
        raise ValueError(f"unknown job state {state!r}; expected one of {JOB_STATE}")
    cur = conn.execute(
        "INSERT INTO jobs (turn_id, executor, handle, script_path, state,"
        " submitted_at, stdout_path, stderr_path) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        (
            turn_id,
            executor,
            handle,
            script_path,
            state,
            submitted_at or utc_now(),
            stdout_path,
            stderr_path,
        ),
    )
    conn.commit()
    return int(cur.lastrowid)


def set_job_state(
    conn: sqlite3.Connection,
    job_id: int,
    state: str,
    *,
    exit_code: int | None = None,
    finished_at: str | None = None,
) -> None:
    if state not in JOB_STATE:
        raise ValueError(f"unknown job state {state!r}; expected one of {JOB_STATE}")
    terminal = state in ("done", "failed")
    conn.execute(
        "UPDATE jobs SET state = ?, exit_code = COALESCE(?, exit_code),"
        " finished_at = COALESCE(?, finished_at) WHERE id = ?",
        (state, exit_code, (finished_at or utc_now()) if terminal else None, job_id),
    )
    conn.commit()


def insert_artifact(
    conn: sqlite3.Connection,
    *,
    turn_id: int,
    path: str,
    kind: str,
    size: int | None = None,
    checksum: str | None = None,
    mtime: str | None = None,
) -> int:
    """Record one artifact, measuring it from disk if not told otherwise.

    The checksum is what lets the index survive the retry-overwrite defect in
    the ``ms_modify`` tools: a second attempt at a stage overwrites the first
    attempt's caltable, so the file itself cannot say which turn produced it.
    """
    if size is None:
        size = path_size(path)
    if checksum is None:
        checksum = checksum_path(path)
    if mtime is None:
        mtime = path_mtime(path)
    cur = conn.execute(
        "INSERT INTO artifacts (turn_id, path, kind, size, checksum, mtime)"
        " VALUES (?, ?, ?, ?, ?, ?)",
        (turn_id, path, kind, size, checksum, mtime),
    )
    conn.commit()
    return int(cur.lastrowid)


def insert_metric(
    conn: sqlite3.Connection,
    *,
    run_id: int,
    name: str,
    value: float | None,
    unit: str | None = None,
    turn_id: int | None = None,
) -> int:
    cur = conn.execute(
        "INSERT INTO metrics (run_id, turn_id, name, value, unit) VALUES (?, ?, ?, ?, ?)",
        (run_id, turn_id, name, value, unit),
    )
    conn.commit()
    return int(cur.lastrowid)


# --------------------------------------------------------------------------
# Queries
# --------------------------------------------------------------------------


def get_run(conn: sqlite3.Connection, run_key: str) -> sqlite3.Row | None:
    return conn.execute("SELECT * FROM runs WHERE run_key = ?", (run_key,)).fetchone()


def active_runs(conn: sqlite3.Connection) -> list[sqlite3.Row]:
    """Runs the driver should still consider. Feeds ``step --all``."""
    return conn.execute("SELECT * FROM runs WHERE status = 'active' ORDER BY started_at").fetchall()


def turns_of(conn: sqlite3.Connection, run_id: int) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT * FROM turns WHERE run_id = ? ORDER BY ordinal", (run_id,)
    ).fetchall()


def last_turn(conn: sqlite3.Connection, run_id: int) -> sqlite3.Row | None:
    return conn.execute(
        "SELECT * FROM turns WHERE run_id = ? ORDER BY ordinal DESC LIMIT 1", (run_id,)
    ).fetchone()


def accepted_turn(conn: sqlite3.Connection, run_id: int, stage: str) -> sqlite3.Row | None:
    """The turn that counted for a stage — the answer to "did the gaincal work".

    At most one row, by the invariant enforced in :func:`set_turn_outcome`.
    """
    return conn.execute(
        "SELECT * FROM turns WHERE run_id = ? AND stage = ? AND outcome = 'accepted'",
        (run_id, stage),
    ).fetchone()


def job_of_turn(conn: sqlite3.Connection, turn_id: int) -> sqlite3.Row | None:
    return conn.execute(
        "SELECT * FROM jobs WHERE turn_id = ? ORDER BY id DESC LIMIT 1", (turn_id,)
    ).fetchone()


def unfinished_jobs(conn: sqlite3.Connection) -> list[sqlite3.Row]:
    """Jobs the driver must poll, and adopt rather than resubmit after a restart."""
    return conn.execute(
        "SELECT j.*, t.run_id, t.ordinal, t.stage FROM jobs j"
        " JOIN turns t ON t.id = j.turn_id"
        " WHERE j.state IN ('pending', 'running') ORDER BY j.id"
    ).fetchall()


def artifacts_of(conn: sqlite3.Connection, turn_id: int) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT * FROM artifacts WHERE turn_id = ? ORDER BY id", (turn_id,)
    ).fetchall()


# --------------------------------------------------------------------------
# The on-disk record, and rebuilding the index from it
# --------------------------------------------------------------------------
#
# write_turn_record and rebuild are two halves of one contract: whatever the
# first writes, the second must be able to turn back into rows. Test them
# against each other, never separately — a divergence here is what turns the
# index into the truth without anyone noticing.


def write_run_record(run_root: Path | str, record: dict) -> Path:
    """Write ``run.json``. Called once, when a run is initialised."""
    ensure_run_dirs(run_root, record["run_key"])
    p = run_json_path(run_root, record["run_key"])
    _atomic_write_json(p, record)
    return p


def write_turn_record(run_root: Path | str, run_key: str, record: dict) -> Path:
    """Write ``turns/NNNN.json`` for one completed turn.

    Written before the rows are inserted, so a crash between the two loses
    nothing that ``rebuild`` cannot recover.
    """
    p = turn_json_path(run_root, run_key, int(record["ordinal"]))
    p.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write_json(p, record)
    return p


def _atomic_write_json(path: Path, obj: dict) -> None:
    """Write via a temporary file and rename, so a reader never sees a partial record."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(obj, indent=2, sort_keys=True))
    tmp.replace(path)


def read_run_records(run_root: Path | str) -> Iterator[dict]:
    """Yield every ``run.json`` under the run root, oldest first."""
    root = Path(run_root)
    if not root.is_dir():
        return
    for p in sorted(root.glob("*/run.json")):
        try:
            yield json.loads(p.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"unreadable run record {p}: {exc}") from exc


def read_turn_records(run_root: Path | str, run_key: str) -> Iterator[dict]:
    """Yield a run's turn records in ordinal order."""
    d = turns_dir(run_root, run_key)
    if not d.is_dir():
        return
    for p in sorted(d.glob("[0-9]*.json")):
        try:
            yield json.loads(p.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"unreadable turn record {p}: {exc}") from exc


def rebuild(conn: sqlite3.Connection, run_root: Path | str) -> dict[str, int]:
    """Reconstruct every table from the records under ``run_root``.

    Destructive to the index and only to the index: it empties the tables and
    replays the files. If this cannot reproduce what the driver wrote, the
    database has become the truth and the design is broken — which is why the
    round trip is the load-bearing test.

    Returns a count of rows written per table.
    """
    for table in ("metrics", "artifacts", "jobs", "turns", "runs"):
        conn.execute(f"DELETE FROM {table}")  # noqa: S608 - fixed table names
    conn.commit()

    counts = dict.fromkeys(("runs", "turns", "jobs", "artifacts", "metrics"), 0)

    for run_rec in read_run_records(run_root):
        run_id = insert_run(
            conn,
            run_key=run_rec["run_key"],
            ms_path=run_rec["ms_path"],
            workdir=run_rec["workdir"],
            backend=run_rec["backend"],
            executor=run_rec["executor"],
            telescope=run_rec.get("telescope"),
            started_at=run_rec.get("started_at"),
            status=run_rec.get("status", "active"),
        )
        if run_rec.get("finished_at") or run_rec.get("status") in ("done", "failed", "needs_human"):
            set_run_status(
                conn,
                run_id,
                run_rec.get("status", "done"),
                finished_at=run_rec.get("finished_at"),
            )
        counts["runs"] += 1

        for turn_rec in read_turn_records(run_root, run_rec["run_key"]):
            turn_id = insert_turn(
                conn,
                run_id=run_id,
                ordinal=int(turn_rec["ordinal"]),
                stage=turn_rec["stage"],
                attempt=int(turn_rec["attempt"]),
                brief=turn_rec.get("brief"),
                decision=turn_rec.get("decision"),
                tool=turn_rec.get("tool"),
                backend=turn_rec.get("backend"),
                model=turn_rec.get("model"),
                tokens_in=turn_rec.get("tokens_in"),
                tokens_out=turn_rec.get("tokens_out"),
                decide_wall_s=turn_rec.get("decide_wall_s"),
                outcome=turn_rec.get("outcome", "pending"),
                started_at=turn_rec.get("started_at"),
                note=turn_rec.get("note"),
            )
            # Replay the closing update too, so the "at most one accepted turn
            # per stage" invariant is re-derived rather than assumed.
            if turn_rec.get("outcome", "pending") != "pending":
                set_turn_outcome(
                    conn,
                    turn_id,
                    turn_rec["outcome"],
                    finished_at=turn_rec.get("finished_at"),
                    note=turn_rec.get("note"),
                )
            counts["turns"] += 1

            job = turn_rec.get("job")
            if job:
                job_id = insert_job(
                    conn,
                    turn_id=turn_id,
                    executor=job["executor"],
                    handle=job["handle"],
                    script_path=job.get("script_path"),
                    state=job.get("state", "pending"),
                    submitted_at=job.get("submitted_at"),
                    stdout_path=job.get("stdout_path"),
                    stderr_path=job.get("stderr_path"),
                )
                if job.get("state") in ("done", "failed"):
                    set_job_state(
                        conn,
                        job_id,
                        job["state"],
                        exit_code=job.get("exit_code"),
                        finished_at=job.get("finished_at"),
                    )
                counts["jobs"] += 1

            for art in turn_rec.get("artifacts", []):
                # Replay the recorded measurements. Re-measuring from disk here
                # would be wrong: a later attempt may have overwritten the file,
                # and the record is what says what this turn actually produced.
                insert_artifact(
                    conn,
                    turn_id=turn_id,
                    path=art["path"],
                    kind=art.get("kind", "other"),
                    size=art.get("size", 0),
                    checksum=art.get("checksum", ""),
                    mtime=art.get("mtime", ""),
                )
                counts["artifacts"] += 1

            for met in turn_rec.get("metrics", []):
                insert_metric(
                    conn,
                    run_id=run_id,
                    turn_id=turn_id,
                    name=met["name"],
                    value=met.get("value"),
                    unit=met.get("unit"),
                )
                counts["metrics"] += 1

    return counts
