"""
gaincal.py — ms_gaincal

Solve for antenna-based gain calibration solutions. Covers three use cases
driven by gaintype and calmode:

  gaintype='K'           → delay solutions (one per antenna per SPW)
  gaintype='G', calmode='p'  → phase-only gains (initial phase for bandpass)
  gaintype='G', calmode='ap' → amplitude+phase gains (final gain calibration)

When execute=False (default), writes a self-contained script to
workdir/<caltable_stem>.py and returns immediately. The user runs it
externally; the caltable is then available for subsequent solve steps.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_modify.exceptions import GaincalFailedError

TOOL_NAME = "ms_gaincal"


def _table_exists(path: str) -> bool:
    p = Path(path)
    return p.exists() and p.is_dir() and any(p.iterdir())


def _script_path(workdir: Path, caltable: str) -> Path:
    stem = Path(caltable).name.replace(".", "_")
    return workdir / f"gaincal_{stem}.py"


def _build_script(
    ms_str: str,
    caltable: str,
    field: str,
    spw: str,
    gaintype: str,
    calmode: str,
    solint: str,
    combine: str,
    refant: str,
    minsnr: float,
    minblperant: int,
    solnorm: bool,
    gaintable: list[str],
    interp: list[str],
    parang: bool,
) -> str:
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_gaincal (ms_modify).
Run with: python {Path(caltable).name.replace(".", "_")}.py
\"\"\"
from casatasks import gaincal

gaincal(
    vis={ms_str!r},
    caltable={caltable!r},
    field={field!r},
    spw={spw!r},
    gaintype={gaintype!r},
    calmode={calmode!r},
    solint={solint!r},
    combine={combine!r},
    refant={refant!r},
    minsnr={minsnr},
    minblperant={minblperant},
    solnorm={solnorm},
    gaintable={gaintable!r},
    interp={interp!r},
    parang={parang},
)
print("Done. Caltable written to: {caltable}")
"""


def run(
    ms_path: str,
    field: str,
    spw: str,
    caltable: str,
    workdir: str,
    gaintype: str = "G",
    calmode: str = "ap",
    solint: str = "inf",
    combine: str = "",
    refant: str = "",
    minsnr: float = 3.0,
    minblperant: int = 4,
    solnorm: bool = False,
    gaintable: list[str] | None = None,
    interp: list[str] | None = None,
    parang: bool = True,
    execute: bool = False,
) -> dict:
    """
    Solve for antenna gain calibration solutions.

    Args:
        ms_path:      Path to the Measurement Set.
        field:        CASA field selection (e.g. '3C147' or '3C147,J0555+3948').
        spw:          CASA SpW/channel selection (e.g. '0:5~58' or '').
        caltable:     Output caltable path (must be inside workdir).
        workdir:      Existing directory; script is written here.
        gaintype:     'G' for complex gains, 'K' for delays.
        calmode:      'p' phase-only, 'a' amp-only, 'ap' amplitude+phase.
        solint:       Solution interval ('int', 'inf', or e.g. '60s').
        combine:      Data axes to combine ('scan', '' etc.).
        refant:       Reference antenna name.
        minsnr:       Minimum SNR for a valid solution (default 3.0).
        minblperant:  Minimum baselines per antenna (default 4).
        solnorm:      Normalise solutions to unit amplitude (default False).
        gaintable:    Prior caltables to apply on-the-fly.
        interp:       Interpolation mode per gaintable entry.
        parang:       Apply parallactic angle correction (default True).
        execute:      If False (default), write script and return.
                      If True, run gaincal in-process.

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes caltable and n_solutions.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    if gaintable is None:
        gaintable = []
    if interp is None:
        interp = [""] * len(gaintable)

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    for gt in gaintable:
        if not Path(gt).exists():
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                f"Prior caltable not found: {gt}",
                ms_path=ms_path,
            )

    script = _script_path(workdir_path, caltable)
    script.write_text(
        _build_script(
            ms_str=ms_str,
            caltable=caltable,
            field=field,
            spw=spw,
            gaintype=gaintype,
            calmode=calmode,
            solint=solint,
            combine=combine,
            refant=refant,
            minsnr=minsnr,
            minblperant=minblperant,
            solnorm=solnorm,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
        )
    )
    casa_calls.append(f"write_script → {script}")

    if not execute:
        warnings.append(
            f"Script written to {script}. Run it externally, "
            "then verify the caltable exists before proceeding."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data={
                "script_path": fmt_field(str(script)),
                "caltable": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
                "gaintype": gaintype,
                "calmode": calmode,
                "solint": solint,
                "combine": combine,
                "refant": refant,
                "field": field,
                "spw": spw,
                "n_prior_tables": len(gaintable),
                "parang": parang,
            },
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True
    try:
        from casatasks import gaincal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.gaincal(field={field!r}, gaintype={gaintype!r}, "
        f"calmode={calmode!r}, solint={solint!r}, refant={refant!r}) → {caltable}"
    )

    try:
        gaincal(
            vis=ms_str,
            caltable=caltable,
            field=field,
            spw=spw,
            gaintype=gaintype,
            calmode=calmode,
            solint=solint,
            combine=combine,
            refant=refant,
            minsnr=minsnr,
            minblperant=minblperant,
            solnorm=solnorm,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
        )
    except Exception as e:
        raise GaincalFailedError(
            f"gaincal raised an exception: {e}\n"
            f"Command: gaincal(vis={ms_str!r}, caltable={caltable!r}, "
            f"field={field!r}, gaintype={gaintype!r}, calmode={calmode!r})",
            ms_path=ms_path,
        ) from e

    if not _table_exists(caltable):
        raise GaincalFailedError(
            f"gaincal did not produce caltable at {caltable!r}. "
            "Possible causes: too few unflagged baselines, wrong field/spw selection, "
            f"or refant {refant!r} not present in the MS.",
            ms_path=ms_path,
        )

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data={
            "script_path": fmt_field(str(script)),
            "caltable": fmt_field(caltable),
            "gaintype": gaintype,
            "calmode": calmode,
            "solint": solint,
            "combine": combine,
            "refant": refant,
            "field": field,
            "spw": spw,
            "n_prior_tables": len(gaintable),
            "parang": parang,
        },
        warnings=warnings,
        casa_calls=casa_calls,
    )
