"""
initial_rflag.py — ms_apply_initial_rflag

Runs rflag + tfcrop together on the residual column (CORRECTED − MODEL)
in a single flagdata(mode='list') pass after the initial bandpass has been
applied and CORRECTED is populated.

Why list mode:
- Single pass over the data — faster on large MSs
- Atomic: both modes commit in one flagmanager version
- Auditable: the list file is the complete record

Script output:
  workdir/initial_rflag_cmds.txt — the flagcmd list
  workdir/initial_rflag.py       — self-contained driver script
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope

TOOL_NAME = "ms_apply_initial_rflag"


def _build_cmds_content(
    timedevscale: float,
    freqdevscale: float,
    timecutoff: float,
    freqcutoff: float,
) -> str:
    """Build the text content for initial_rflag_cmds.txt."""
    lines = [
        f"mode='rflag' datacolumn='residual' timedevscale={timedevscale} freqdevscale={freqdevscale} action='apply'",
        f"mode='tfcrop' datacolumn='residual' timecutoff={timecutoff} freqcutoff={freqcutoff} action='apply'",
    ]
    return "\n".join(lines) + "\n"


def _build_script(
    ms_str: str,
    cmds_path: str,
) -> str:
    """Return a self-contained initial_rflag Python script."""
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_apply_initial_rflag (ms_modify).
Run with: python initial_rflag.py

Requires: CORRECTED and MODEL columns populated (run initial_bandpass.py first).
flagbackup=True saves a versioned flag backup automatically before flagging.
\"\"\"
from casatasks import flagdata

ms_path = {ms_str!r}
cmds_file = {cmds_path!r}

# Single atomic pass: rflag + tfcrop on residual column.
# flagbackup=True creates a versioned backup in the MS .flagversions directory.
flagdata(
    vis=ms_path,
    mode="list",
    inpfile=cmds_file,
    flagbackup=True,
)
print("Initial rflag + tfcrop complete.")
print("Use ms_flag_summary to inspect the flag delta,")
print("and ms_residual_stats to verify the residual distribution.")
"""


def run(
    ms_path: str,
    workdir: str,
    timedevscale: float = 5.0,
    freqdevscale: float = 5.0,
    timecutoff: float = 4.0,
    freqcutoff: float = 4.0,
    execute: bool = False,
) -> dict:
    """
    Generate (and optionally execute) initial rflag + tfcrop on residuals.

    Args:
        ms_path:      Path to the MS (CORRECTED + MODEL must exist).
        workdir:      Existing directory for the generated scripts.
        timedevscale: rflag time deviation threshold (default 5.0).
        freqdevscale: rflag frequency deviation threshold (default 5.0).
        timecutoff:   tfcrop time deviation threshold (default 4.0).
        freqcutoff:   tfcrop frequency deviation threshold (default 4.0).
        execute:      If False (default), write scripts and return.
                      If True, run flagdata(mode='list') in-process.

    Returns:
        Standard response envelope. Always includes cmds_path and script_path.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    cmds_path = str(workdir_path / "initial_rflag_cmds.txt")
    script_path = str(workdir_path / "initial_rflag.py")

    # Always write the flag command list
    cmds_content = _build_cmds_content(timedevscale, freqdevscale, timecutoff, freqcutoff)
    Path(cmds_path).write_text(cmds_content)
    casa_calls.append(f"write_cmds → {cmds_path}")

    # Always write the script
    script_content = _build_script(ms_str, cmds_path)
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "cmds_path": fmt_field(cmds_path),
        "script_path": fmt_field(script_path),
        "rflag_timedevscale": timedevscale,
        "rflag_freqdevscale": freqdevscale,
        "tfcrop_timecutoff": timecutoff,
        "tfcrop_freqcutoff": freqcutoff,
        "datacolumn": "residual",
    }

    if not execute:
        warnings.append(
            f"Scripts written to {workdir}. "
            "Ensure initial_bandpass.py has been run first (CORRECTED + MODEL must exist). "
            "Then run initial_rflag.py externally and call ms_flag_summary to capture the delta."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run in-process
    try:
        from casatasks import flagdata  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(f"casatasks.flagdata(mode='list', inpfile='{cmds_path}', flagbackup=True)")
    try:
        flagdata(
            vis=ms_str,
            mode="list",
            inpfile=cmds_path,
            flagbackup=True,
        )
    except Exception as exc:
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"flagdata(mode='list') for initial rflag failed: {exc}",
            ms_path=ms_path,
        ) from exc

    base_data["flags_applied"] = fmt_field(True)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
