"""
polcal.py — ms_polcal

Solve for polarisation calibration solutions. Supports three poltype modes:

  poltype='Df'    → D-term leakage calibration (source polarisation unknown).
  poltype='Df+QU' → D-term leakage + source Q,U (both unknowns solved together).
  poltype='Xf'    → Position angle calibration (requires angle cal model set via setjy).

When execute=False (default), writes a self-contained script to
workdir/polcal_<caltable_stem>.py and returns immediately. The user runs it
externally; the caltable is then available for subsequent solve steps.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_modify.exceptions import PolcalFailedError

TOOL_NAME = "ms_polcal"


def _table_exists(path: str) -> bool:
    p = Path(path)
    return p.exists() and p.is_dir() and any(p.iterdir())


def _script_path(workdir: Path, caltable: str) -> Path:
    stem = Path(caltable).name.replace(".", "_")
    return workdir / f"polcal_{stem}.py"


def _build_script(
    ms_str: str,
    caltable: str,
    field: str,
    poltype: str,
    solint: str,
    combine: str,
    refant: str,
    gaintable: list[str],
    interp: list[str],
    parang: bool,
) -> str:
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_polcal (ms_modify).
Run with: python {Path(caltable).name.replace(".", "_")}.py
\"\"\"
import os
import shutil
from casatasks import polcal

if os.path.exists({caltable!r}):
    shutil.rmtree({caltable!r})
polcal(
    vis={ms_str!r},
    caltable={caltable!r},
    field={field!r},
    poltype={poltype!r},
    solint={solint!r},
    combine={combine!r},
    refant={refant!r},
    gaintable={gaintable!r},
    interp={interp!r},
    parang={parang},
)
print("Done. Caltable written to: {caltable}")
"""


def run(
    ms_path: str,
    field: str,
    caltable: str,
    workdir: str,
    poltype: str,
    solint: str = "inf",
    combine: str = "scan",
    refant: str = "",
    gaintable: list[str] | None = None,
    interp: list[str] | None = None,
    parang: bool = True,
    execute: bool = False,
) -> dict:
    """
    Solve for polarisation calibration solutions.

    Args:
        ms_path:      Path to the Measurement Set.
        field:        CASA field selection for calibrator.
        caltable:     Output caltable path.
        workdir:      Existing directory; script is written here.
        poltype:      'Df' (D-terms), 'Df+QU' (D-terms + source pol), or 'Xf' (position angle).
        solint:       Solution interval (default 'inf').
        combine:      Data axes to combine (default 'scan').
        refant:       Reference antenna name.
        gaintable:    Prior caltables to apply on-the-fly.
        interp:       Interpolation mode per gaintable entry.
        parang:       Apply parallactic angle correction (default True). **Critical for polcal.**
        execute:      If False (default), write script and return.
                      If True, run polcal in-process.

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes caltable path.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    if poltype not in ("Df", "Df+QU", "Xf"):
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"poltype must be 'Df', 'Df+QU', or 'Xf'; got {poltype!r}",
            ms_path=ms_path,
        )

    if gaintable is None:
        gaintable = []
    if interp is None:
        interp = [""] * len(gaintable)

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    for gt in gaintable:
        if not Path(gt).exists():
            from ms_inspect.exceptions import ComputationError

            raise ComputationError(
                f"Prior caltable not found: {gt}",
                ms_path=ms_path,
            )

    script = _script_path(workdir_path, caltable)
    script.write_text(
        _build_script(
            ms_str=ms_str,
            caltable=caltable,
            field=field,
            poltype=poltype,
            solint=solint,
            combine=combine,
            refant=refant,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
        )
    )
    casa_calls.append(f"write_script → {script}")

    if not execute:
        warnings.append(
            f"Script written to {script}. Run it externally, "
            "then verify the caltable exists before proceeding."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data={
                "script_path": fmt_field(str(script)),
                "caltable": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
                "poltype": poltype,
                "field": field,
                "solint": solint,
                "combine": combine,
                "refant": refant,
                "n_prior_tables": len(gaintable),
                "parang": parang,
            },
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True
    try:
        from casatasks import polcal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.polcal(field={field!r}, poltype={poltype!r}, "
        f"solint={solint!r}, refant={refant!r}) → {caltable}"
    )

    try:
        polcal(
            vis=ms_str,
            caltable=caltable,
            field=field,
            poltype=poltype,
            solint=solint,
            combine=combine,
            refant=refant,
            gaintable=gaintable,
            interp=interp,
            parang=parang,
        )
    except Exception as e:
        raise PolcalFailedError(
            f"polcal raised an exception: {e}\n"
            f"Command: polcal(vis={ms_str!r}, caltable={caltable!r}, "
            f"field={field!r}, poltype={poltype!r})",
            ms_path=ms_path,
        ) from e

    if not _table_exists(caltable):
        raise PolcalFailedError(
            f"polcal did not produce caltable at {caltable!r}. "
            f"Possible causes: too few unflagged data, insufficient parallactic angle coverage, "
            f"or refant {refant!r} not present in the MS.",
            ms_path=ms_path,
        )

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data={
            "script_path": fmt_field(str(script)),
            "caltable": fmt_field(caltable),
            "poltype": poltype,
            "field": field,
            "solint": solint,
            "combine": combine,
            "refant": refant,
            "n_prior_tables": len(gaintable),
            "parang": parang,
        },
        warnings=warnings,
        casa_calls=casa_calls,
    )
