"""
postcal_flag.py — ms_postcal_flag

Post-calibration RFI flagging on the phase calibrator AND science target, after
the final applycal. The pre-cal pipeline flags calibrators only; this routine
extends flagging to the fields that were never cleaned, and bakes the SpW-triage
decision (from ms_spw_amp_severity, reasoned in skill 13) into the FLAG column.

One atomic flagdata(mode='list') pass over the CORRECTED column:
  1. clip      — optional ceiling on |CORRECTED| to kill egregious outliers
                 before the autoflaggers compute their statistics
  2. tfcrop    — on the SpWs being KEPT (salvage localized RFI, preserve bandwidth)
  3. rflag     — likewise
  4. manual    — fully flag the drop-tier SpWs (so all downstream steps respect it)

field is REQUIRED. Flagging CORRECTED on fields whose calibration is not valid
flags almost everything; the caller scopes this to the phase cal + target.

Script output:
  workdir/postcal_flag_cmds.txt — the flagcmd list (complete audit record)
  workdir/postcal_flag.py       — self-contained driver script
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, normalize_spw_sel, response_envelope

TOOL_NAME = "ms_postcal_flag"


def _build_cmds_content(
    field: str,
    keep_spw: str,
    drop_spw: str,
    datacolumn: str,
    clipmax: float | None,
    timedevscale: float,
    freqdevscale: float,
    timecutoff: float,
    freqcutoff: float,
) -> str:
    lines: list[str] = []
    if clipmax is not None:
        lines.append(
            f"mode='clip' field={field!r} datacolumn={datacolumn!r} "
            f"clipminmax=[0.0,{clipmax}] clipoutside=True"
        )
    spw_clause = f" spw={keep_spw!r}" if keep_spw else ""
    lines.append(
        f"mode='tfcrop' field={field!r}{spw_clause} datacolumn={datacolumn!r} "
        f"timecutoff={timecutoff} freqcutoff={freqcutoff}"
    )
    lines.append(
        f"mode='rflag' field={field!r}{spw_clause} datacolumn={datacolumn!r} "
        f"timedevscale={timedevscale} freqdevscale={freqdevscale}"
    )
    if drop_spw:
        lines.append(f"mode='manual' field={field!r} spw={drop_spw!r}")
    return "\n".join(lines) + "\n"


def _build_script(ms_str: str, cmds_path: str) -> str:
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_postcal_flag (ms_modify).
Run with: python postcal_flag.py

Requires: CORRECTED populated on the selected fields (final applycal done).
For the SpW-drop decisions to be honoured everywhere, run applycal with
applymode='calonly' so caltable flags do not pre-empt these decisions.
flagbackup=True saves a versioned backup automatically before flagging.
\"\"\"
from casatasks import flagdata

ms_path = {ms_str!r}
cmds_file = {cmds_path!r}

flagdata(
    vis=ms_path,
    mode="list",
    inpfile=cmds_file,
    flagbackup=True,
)
print("Post-calibration flagging complete.")
print("Use ms_flag_summary for the flag delta and ms_spw_amp_severity to re-measure.")
"""


def run(
    ms_path: str,
    workdir: str,
    field: str,
    keep_spw: str = "",
    drop_spw: str = "",
    datacolumn: str = "corrected",
    clipmax: float | None = None,
    timedevscale: float = 5.0,
    freqdevscale: float = 5.0,
    timecutoff: float = 4.0,
    freqcutoff: float = 4.0,
    execute: bool = False,
) -> dict:
    """
    Generate (and optionally execute) post-calibration RFI flagging.

    Args:
        ms_path:      Path to the MS (CORRECTED populated on the selected fields).
        workdir:      Existing directory for the generated scripts.
        field:        REQUIRED. The field(s) to flag — the phase calibrator and/or
                      science target whose CORRECTED column is valid after the final
                      applycal. An all-field pass over fields without valid CORRECTED
                      flags almost everything.
        keep_spw:     CASA SpW selection for the SpWs being KEPT — tfcrop + rflag run
                      on these to salvage localized RFI. Empty = all SpWs.
        drop_spw:     CASA SpW selection for the drop-tier SpWs — fully flagged via a
                      manual command so downstream imaging/calibration respects it.
                      Empty = drop nothing.
        datacolumn:   Column to flag on (default 'corrected').
        clipmax:      Optional ceiling on |CORRECTED| (clipminmax=[0, clipmax],
                      clipoutside=True) applied first to remove egregious outliers
                      before the autoflaggers compute statistics. None = no clip.
        timedevscale: rflag time deviation threshold (default 5.0).
        freqdevscale: rflag frequency deviation threshold (default 5.0).
        timecutoff:   tfcrop time deviation threshold (default 4.0).
        freqcutoff:   tfcrop frequency deviation threshold (default 4.0).
        execute:      If False (default), write scripts and return.
                      If True, run flagdata(mode='list') in-process.

    Returns:
        Standard envelope. Always includes cmds_path and script_path.
    """
    field = normalize_field_sel(field)
    keep_spw = normalize_spw_sel(keep_spw)
    drop_spw = normalize_spw_sel(drop_spw)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    if not field or not str(field).strip():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            "field is required. Scope post-cal flagging to the phase calibrator and/or "
            "science target whose CORRECTED column is valid after the final applycal. "
            "An all-field pass over fields without valid CORRECTED flags almost everything.",
            ms_path=ms_path,
        )

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    cmds_path = str(workdir_path / "postcal_flag_cmds.txt")
    script_path = str(workdir_path / "postcal_flag.py")

    cmds_content = _build_cmds_content(
        field,
        keep_spw,
        drop_spw,
        datacolumn,
        clipmax,
        timedevscale,
        freqdevscale,
        timecutoff,
        freqcutoff,
    )
    Path(cmds_path).write_text(cmds_content)
    casa_calls.append(f"write_cmds → {cmds_path}")

    script_content = _build_script(ms_str, cmds_path)
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "cmds_path": fmt_field(cmds_path),
        "script_path": fmt_field(script_path),
        "field": fmt_field(field),
        "keep_spw": keep_spw,
        "drop_spw": drop_spw,
        "datacolumn": datacolumn,
        "clipmax": clipmax,
        "rflag_timedevscale": timedevscale,
        "rflag_freqdevscale": freqdevscale,
        "tfcrop_timecutoff": timecutoff,
        "tfcrop_freqcutoff": freqcutoff,
    }

    if not execute:
        warnings.append(
            f"Scripts written to {workdir}. Ensure the final applycal has populated "
            "CORRECTED on the selected fields (run applycal with applymode='calonly' so "
            "these SpW-drop decisions own the FLAG column). Then run postcal_flag.py "
            "externally and call ms_flag_summary to capture the delta."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    try:
        from casatasks import flagdata  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(f"casatasks.flagdata(mode='list', inpfile='{cmds_path}', flagbackup=True)")
    try:
        flagdata(
            vis=ms_str,
            mode="list",
            inpfile=cmds_path,
            flagbackup=True,
        )
    except Exception as exc:
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"flagdata(mode='list') for post-cal flagging failed: {exc}",
            ms_path=ms_path,
        ) from exc

    base_data["flags_applied"] = fmt_field(True)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
