"""
priorcals.py — ms_generate_priorcals

Generates the four deterministic prior calibration tables that must be
prepended to every subsequent gaincal/bandpass/applycal call.

Tables generated (in order):
  1. gain_curves.gc   — gencal(caltype='gc')   VLA elevation gain curves
  2. opacities.opac   — gencal(caltype='opac')  Per-SPW zenith opacity
  3. requantizer.rq   — gencal(caltype='rq')    VLA WIDAR requantizer
                        (attempted iff SYSPOWER subtable has rows — only
                        WIDAR writes SYSPOWER; an observation date proxy
                        misclassifies 2010-11 commissioning-era data)
  4. antpos.ap        — gencal(caltype='antpos') Antenna position corrections
                        (skipped if gencal returns 0-row table)

The returned 'priorcals' list is the exact sequence to pass as
priorcals= to ms_initial_bandpass.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope

TOOL_NAME = "ms_generate_priorcals"


def _table_nrows(path: str) -> int:
    """Return nrows for a CASA table, or 0 on any error."""
    try:
        from casatools import table  # type: ignore[import]

        tb = table()
        tb.open(path, nomodify=True)
        n = tb.nrows()
        tb.close()
        return int(n)
    except Exception:
        return 0


def _build_script(
    ms_str: str,
    gc_table: str,
    opac_table: str,
    rq_table: str,
    antpos_table: str,
) -> str:
    """Return a self-contained priorcals Python script."""
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_generate_priorcals (ms_modify).
Run with: python priorcals.py
\"\"\"
import os
import shutil
from casatasks import gencal, plotweather
from casatools import table

ms_path = {ms_str!r}
gc_table = {gc_table!r}
opac_table = {opac_table!r}
rq_table = {rq_table!r}
antpos_table = {antpos_table!r}


def _table_nrows(path):
    try:
        tb = table()
        tb.open(path, nomodify=True)
        n = tb.nrows()
        tb.close()
        return n
    except Exception:
        return 0


priorcals = []
skipped = []
skip_reasons = {{}}

# 1 — Gain curves
print("Generating gain curves...")
if os.path.exists(gc_table):
    shutil.rmtree(gc_table)
try:
    gencal(vis=ms_path, caltable=gc_table, caltype="gc")
except Exception as _exc:
    print(f"  gc: gencal raised {{_exc!r}} — skipped")
    skipped.append("gain_curves.gc")
    skip_reasons["gain_curves.gc"] = str(_exc)
if "gain_curves.gc" not in skip_reasons:
    if _table_nrows(gc_table) > 0:
        priorcals.append(gc_table)
        print(f"  gc: {{gc_table}}")
    else:
        skipped.append("gain_curves.gc")
        skip_reasons["gain_curves.gc"] = "gencal returned 0-row table"
        print("  gc: empty — skipped")

# 2 — Opacities
# gencal(caltype='opac') does NOT compute tau; it only writes the values passed
# in parameter=. Derive per-SPW zenith opacities from the WEATHER table with
# plotweather(doPlot=False), then feed them to gencal with a matching spw list.
print("Generating opacities...")
if os.path.exists(opac_table):
    shutil.rmtree(opac_table)
try:
    _tau = list(plotweather(vis=ms_path, doPlot=False))
    _spw = ",".join(str(_i) for _i in range(len(_tau)))
    gencal(vis=ms_path, caltable=opac_table, caltype="opac", spw=_spw, parameter=_tau)
    print(f"  opac: tau per spw = {{_tau}}")
except Exception as _exc:
    print(f"  opac: plotweather/gencal raised {{_exc!r}} — skipped")
    skipped.append("opacities.opac")
    skip_reasons["opacities.opac"] = "no WEATHER subtable — cannot compute zenith opacity"
    print("  opac: skipped (no WEATHER subtable)")
else:
    try:
        taus = plotweather(vis=ms_path, doPlot=False)
        spw_sel = ",".join(str(i) for i in range(len(taus)))
        gencal(vis=ms_path, caltable=opac_table, caltype="opac", spw=spw_sel, parameter=taus)
    except Exception as _exc:
        print(f"  opac: raised {{_exc!r}} — skipped")
        skipped.append("opacities.opac")
        skip_reasons["opacities.opac"] = str(_exc)
    if "opacities.opac" not in skip_reasons:
        if _table_nrows(opac_table) > 0:
            priorcals.append(opac_table)
            print(f"  opac: {{opac_table}} (tau={{[round(t, 4) for t in taus]}})")
        else:
            skipped.append("opacities.opac")
            skip_reasons["opacities.opac"] = "gencal returned 0-row table"
            print("  opac: empty — skipped")

# 3 — Requantizer (WIDAR data only; SYSPOWER subtable is written only by WIDAR)
if _table_nrows(ms_path + "/SYSPOWER") > 0:
    print("Generating requantizer corrections...")
    if os.path.exists(rq_table):
        shutil.rmtree(rq_table)
    try:
        gencal(vis=ms_path, caltable=rq_table, caltype="rq")
    except Exception as _exc:
        print(f"  rq: gencal raised {{_exc!r}} — skipped")
        skipped.append("requantizer.rq")
        skip_reasons["requantizer.rq"] = str(_exc)
    if "requantizer.rq" not in skip_reasons:
        if _table_nrows(rq_table) > 0:
            priorcals.append(rq_table)
            print(f"  rq: {{rq_table}}")
        else:
            skipped.append("requantizer.rq")
            skip_reasons["requantizer.rq"] = "gencal returned 0-row table"
            print("  rq: empty — skipped")
else:
    skipped.append("requantizer.rq")
    skip_reasons["requantizer.rq"] = "no SYSPOWER subtable (pre-WIDAR data)"
    print("  rq: skipped (no SYSPOWER subtable — pre-WIDAR data)")

# 4 — Antenna positions
print("Generating antenna position corrections...")
if os.path.exists(antpos_table):
    shutil.rmtree(antpos_table)
try:
    gencal(vis=ms_path, caltable=antpos_table, caltype="antpos")
except Exception as _exc:
    print(f"  antpos: gencal raised {{_exc!r}} — skipped")
    skipped.append("antpos.ap")
    skip_reasons["antpos.ap"] = str(_exc)
if "antpos.ap" not in skip_reasons:
    if _table_nrows(antpos_table) > 0:
        priorcals.append(antpos_table)
        print(f"  antpos: {{antpos_table}}")
    else:
        skipped.append("antpos.ap")
        skip_reasons["antpos.ap"] = "gencal returned 0-row table"
        print("  antpos: empty — skipped (no corrections needed)")

print()
print(f"priorcals = {{priorcals}}")
print(f"skipped   = {{skipped}}")
print("Pass priorcals= to ms_initial_bandpass.")
"""


def run(
    ms_path: str,
    workdir: str,
    execute: bool = False,
) -> dict:
    """
    Generate prior calibration tables (gc, opac, rq, antpos).

    Args:
        ms_path:  Path to the MS (calibrators.ms or full MS).
        workdir:  Existing directory for caltable output.
        execute:  If False (default), write priorcals.py and return.
                  If True, run gencal in-process for all four tables.

    Returns:
        Standard response envelope. execute=False: script_path only.
        execute=True: priorcals list and skipped list.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    gc_table = str(workdir_path / "gain_curves.gc")
    opac_table = str(workdir_path / "opacities.opac")
    rq_table = str(workdir_path / "requantizer.rq")
    antpos_table = str(workdir_path / "antpos.ap")
    script_path = str(workdir_path / "priorcals.py")

    script_content = _build_script(
        ms_str=ms_str,
        gc_table=gc_table,
        opac_table=opac_table,
        rq_table=rq_table,
        antpos_table=antpos_table,
    )
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    if not execute:
        data = {
            "script_path": fmt_field(script_path),
            "priorcals": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
            "skipped": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
            "expected_tables": fmt_field([gc_table, opac_table, rq_table, antpos_table]),
        }
        warnings.append(
            f"Script written to {script_path}. Run it externally, "
            "then call ms_verify_priorcals to confirm the output tables."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run gencal in-process
    try:
        from casatasks import gencal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    priorcals: list[str] = []
    skipped: list[str] = []
    skip_reasons: dict[str, str] = {}

    def _run_gencal(caltable: str, caltype: str, label: str) -> bool:
        casa_calls.append(f"casatasks.gencal(caltype='{caltype}') → {label}")
        try:
            gencal(vis=ms_str, caltable=caltable, caltype=caltype)
        except Exception as exc:
            warnings.append(f"gencal(caltype='{caltype}') raised: {exc}")
            return False
        return _table_nrows(caltable) > 0

    # gc
    if _run_gencal(gc_table, "gc", "gain_curves.gc"):
        priorcals.append(gc_table)
    else:
        skipped.append("gain_curves.gc")
        skip_reasons["gain_curves.gc"] = "gencal returned 0-row table"

    # opac — per-SPW zenith opacity computed from the WEATHER subtable via
    # plotweather, then written with gencal(caltype='opac', parameter=taus).
    # gencal opac is a *manual* caltype: without parameter it writes a 0-row
    # table, so opacity must be computed first. Genuinely skipped only when
    # there is no WEATHER subtable (e.g. some older/imported MSs).
    casa_calls.append("tb.open(WEATHER) → nrows (opacity check)")
    if _table_nrows(ms_str + "/WEATHER") == 0:
        skipped.append("opacities.opac")
        skip_reasons["opacities.opac"] = "no WEATHER subtable — cannot compute zenith opacity"
    else:
        try:
            from casatasks import plotweather  # type: ignore[import]

            casa_calls.append("casatasks.plotweather(doPlot=False) → zenith opacities")
            taus = plotweather(vis=ms_str, doPlot=False)
            spw_sel = ",".join(str(i) for i in range(len(taus)))
            casa_calls.append(
                f"casatasks.gencal(caltype='opac', spw='{spw_sel}', parameter=taus)"
            )
            gencal(vis=ms_str, caltable=opac_table, caltype="opac", spw=spw_sel, parameter=taus)
        except Exception as exc:
            warnings.append(f"opacity computation failed: {exc}")
            skipped.append("opacities.opac")
            skip_reasons["opacities.opac"] = str(exc)
        if "opacities.opac" not in skip_reasons:
            if _table_nrows(opac_table) > 0:
                priorcals.append(opac_table)
            else:
                skipped.append("opacities.opac")
                skip_reasons["opacities.opac"] = "gencal returned 0-row table"

    # rq — WIDAR data only. SYSPOWER is written only by the WIDAR correlator,
    # so its presence is the discriminator; an observation-date cutoff
    # misclassifies 2010-11 commissioning-era WIDAR data as pre-WIDAR.
    casa_calls.append("tb.open(SYSPOWER) → nrows (rq WIDAR check)")
    if _table_nrows(ms_str + "/SYSPOWER") > 0:
        if _run_gencal(rq_table, "rq", "requantizer.rq"):
            priorcals.append(rq_table)
        else:
            skipped.append("requantizer.rq")
            skip_reasons["requantizer.rq"] = "gencal returned 0-row table"
    else:
        skipped.append("requantizer.rq")
        skip_reasons["requantizer.rq"] = "no SYSPOWER subtable (pre-WIDAR data)"

    # antpos
    if _run_gencal(antpos_table, "antpos", "antpos.ap"):
        priorcals.append(antpos_table)
    else:
        skipped.append("antpos.ap")
        skip_reasons["antpos.ap"] = "gencal returned 0-row table"

    data = {
        "script_path": fmt_field(script_path),
        "priorcals": fmt_field(priorcals),
        "skipped": fmt_field(skipped),
        "skip_reasons": fmt_field(skip_reasons),
        "n_priorcals": len(priorcals),
    }

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
