"""
priorcals.py — ms_generate_priorcals

Generates the four deterministic prior calibration tables that must be
prepended to every subsequent gaincal/bandpass/applycal call.

Tables generated (in order):
  1. gain_curves.gc   — gencal(caltype='gc')   VLA elevation gain curves
  2. opacities.opac   — gencal(caltype='opac')  Per-SPW zenith opacity
  3. requantizer.rq   — gencal(caltype='rq')    Post-2011 VLA requantizer
                        (MJD >= 55616.6 only — older data skip silently)
  4. antpos.ap        — gencal(caltype='antpos') Antenna position corrections
                        (skipped if gencal returns 0-row table)

The returned 'priorcals' list is the exact sequence to pass as
priorcals= to ms_initial_bandpass.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope

TOOL_NAME = "ms_generate_priorcals"

# MJD threshold for VLA WIDAR requantizer (2011-03-01 ≈ MJD 55616.6)
_RQ_MJD_THRESHOLD = 55616.6


def _table_nrows(path: str) -> int:
    """Return nrows for a CASA table, or 0 on any error."""
    try:
        from casatools import table  # type: ignore[import]
        tb = table()
        tb.open(path, nomodify=True)
        n = tb.nrows()
        tb.close()
        return int(n)
    except Exception:
        return 0


def _build_script(
    ms_str: str,
    gc_table: str,
    opac_table: str,
    rq_table: str,
    antpos_table: str,
    rq_mjd_threshold: float,
) -> str:
    """Return a self-contained priorcals Python script."""
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_generate_priorcals (ms_modify).
Run with: python priorcals.py
\"\"\"
import os
from casatasks import gencal
from casatools import table

ms_path = {ms_str!r}
gc_table = {gc_table!r}
opac_table = {opac_table!r}
rq_table = {rq_table!r}
antpos_table = {antpos_table!r}


def _table_nrows(path):
    try:
        tb = table()
        tb.open(path, nomodify=True)
        n = tb.nrows()
        tb.close()
        return n
    except Exception:
        return 0


def _get_obs_mjd(vis):
    \"\"\"Read start MJD from OBSERVATION subtable.\"\"\"
    try:
        tb = table()
        tb.open(vis + "/OBSERVATION", nomodify=True)
        time_range = tb.getcol("TIME_RANGE")
        tb.close()
        return float(time_range[0][0]) / 86400.0  # seconds → days
    except Exception:
        return None


priorcals = []
skipped = []
skip_reasons = {{}}

# 1 — Gain curves
print("Generating gain curves...")
gencal(vis=ms_path, caltable=gc_table, caltype="gc")
if _table_nrows(gc_table) > 0:
    priorcals.append(gc_table)
    print(f"  gc: {{gc_table}}")
else:
    skipped.append("gain_curves.gc")
    skip_reasons["gain_curves.gc"] = "gencal returned 0-row table"
    print("  gc: empty — skipped")

# 2 — Opacities
print("Generating opacities...")
gencal(vis=ms_path, caltable=opac_table, caltype="opac")
if _table_nrows(opac_table) > 0:
    priorcals.append(opac_table)
    print(f"  opac: {{opac_table}}")
else:
    skipped.append("opacities.opac")
    skip_reasons["opacities.opac"] = "gencal returned 0-row table"
    print("  opac: empty — skipped")

# 3 — Requantizer (VLA post-2011 only)
obs_mjd = _get_obs_mjd(ms_path)
if obs_mjd is None or obs_mjd >= {rq_mjd_threshold}:
    print("Generating requantizer corrections...")
    gencal(vis=ms_path, caltable=rq_table, caltype="rq")
    if _table_nrows(rq_table) > 0:
        priorcals.append(rq_table)
        print(f"  rq: {{rq_table}}")
    else:
        skipped.append("requantizer.rq")
        skip_reasons["requantizer.rq"] = "gencal returned 0-row table"
        print("  rq: empty — skipped")
else:
    skipped.append("requantizer.rq")
    skip_reasons["requantizer.rq"] = f"MJD {{obs_mjd:.1f}} < {rq_mjd_threshold} (pre-WIDAR)"
    print(f"  rq: skipped (pre-WIDAR, MJD={{obs_mjd:.1f}})")

# 4 — Antenna positions
print("Generating antenna position corrections...")
gencal(vis=ms_path, caltable=antpos_table, caltype="antpos")
if _table_nrows(antpos_table) > 0:
    priorcals.append(antpos_table)
    print(f"  antpos: {{antpos_table}}")
else:
    skipped.append("antpos.ap")
    skip_reasons["antpos.ap"] = "gencal returned 0-row table"
    print("  antpos: empty — skipped (no corrections needed)")

print()
print(f"priorcals = {{priorcals}}")
print(f"skipped   = {{skipped}}")
print("Pass priorcals= to ms_initial_bandpass.")
"""


def run(
    ms_path: str,
    workdir: str,
    execute: bool = False,
) -> dict:
    """
    Generate prior calibration tables (gc, opac, rq, antpos).

    Args:
        ms_path:  Path to the MS (calibrators.ms or full MS).
        workdir:  Existing directory for caltable output.
        execute:  If False (default), write priorcals.py and return.
                  If True, run gencal in-process for all four tables.

    Returns:
        Standard response envelope. execute=False: script_path only.
        execute=True: priorcals list and skipped list.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError
        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    gc_table = str(workdir_path / "gain_curves.gc")
    opac_table = str(workdir_path / "opacities.opac")
    rq_table = str(workdir_path / "requantizer.rq")
    antpos_table = str(workdir_path / "antpos.ap")
    script_path = str(workdir_path / "priorcals.py")

    script_content = _build_script(
        ms_str=ms_str,
        gc_table=gc_table,
        opac_table=opac_table,
        rq_table=rq_table,
        antpos_table=antpos_table,
        rq_mjd_threshold=_RQ_MJD_THRESHOLD,
    )
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    if not execute:
        data = {
            "script_path": fmt_field(script_path),
            "priorcals": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
            "skipped": fmt_field(None, flag="UNAVAILABLE", note="script not yet executed"),
            "expected_tables": fmt_field([gc_table, opac_table, rq_table, antpos_table]),
        }
        warnings.append(
            f"Script written to {script_path}. Run it externally, "
            "then call ms_verify_priorcals to confirm the output tables."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run gencal in-process
    try:
        from casatasks import gencal  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError
        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    priorcals: list[str] = []
    skipped: list[str] = []
    skip_reasons: dict[str, str] = {}

    # Determine obs MJD for rq decision
    obs_mjd: float | None = None
    try:
        from ms_inspect.util.casa_context import open_table
        with open_table(ms_str + "/OBSERVATION") as tb:
            time_range = tb.getcol("TIME_RANGE")
            obs_mjd = float(time_range[0][0]) / 86400.0
        casa_calls.append("tb.open(OBSERVATION) → TIME_RANGE (for rq MJD check)")
    except Exception as exc:
        warnings.append(f"Could not read obs MJD for rq check: {exc}. Attempting rq generation.")

    def _run_gencal(caltable: str, caltype: str, label: str) -> bool:
        casa_calls.append(f"casatasks.gencal(caltype='{caltype}') → {label}")
        try:
            gencal(vis=ms_str, caltable=caltable, caltype=caltype)
        except Exception as exc:
            warnings.append(f"gencal(caltype='{caltype}') raised: {exc}")
            return False
        return _table_nrows(caltable) > 0

    # gc
    if _run_gencal(gc_table, "gc", "gain_curves.gc"):
        priorcals.append(gc_table)
    else:
        skipped.append("gain_curves.gc")
        skip_reasons["gain_curves.gc"] = "gencal returned 0-row table"

    # opac
    if _run_gencal(opac_table, "opac", "opacities.opac"):
        priorcals.append(opac_table)
    else:
        skipped.append("opacities.opac")
        skip_reasons["opacities.opac"] = "gencal returned 0-row table"

    # rq — only for post-2011 data
    do_rq = obs_mjd is None or obs_mjd >= _RQ_MJD_THRESHOLD
    if do_rq:
        if _run_gencal(rq_table, "rq", "requantizer.rq"):
            priorcals.append(rq_table)
        else:
            skipped.append("requantizer.rq")
            skip_reasons["requantizer.rq"] = "gencal returned 0-row table"
    else:
        skipped.append("requantizer.rq")
        skip_reasons["requantizer.rq"] = (
            f"MJD {obs_mjd:.1f} < {_RQ_MJD_THRESHOLD} (pre-WIDAR era)"
        )

    # antpos
    if _run_gencal(antpos_table, "antpos", "antpos.ap"):
        priorcals.append(antpos_table)
    else:
        skipped.append("antpos.ap")
        skip_reasons["antpos.ap"] = "gencal returned 0-row table"

    data = {
        "script_path": fmt_field(script_path),
        "priorcals": fmt_field(priorcals),
        "skipped": fmt_field(skipped),
        "skip_reasons": fmt_field(skip_reasons),
        "n_priorcals": len(priorcals),
    }

    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
