"""
setjy_polcal.py — ms_setjy_polcal

Sets the full polarization model (Stokes I + polindex + polangle) for a
polarization angle calibrator using setjy(standard='manual').

Logic:
  1. Look up the calibrator in the pol_calibrators catalogue.
  2. Fit polynomial coefficients via fit_from_catalogue.
  3. Write a setjy(standard='manual') CASA script to workdir/setjy_polcal.py.
  4. Optionally run setjy in-process when execute=True.

CASA coefficient convention (ascending order):
  polindex = [c0, c1, c2, ...]   where c0 = fractional pol at reffreq
  polangle = [c0, c1, c2, ...]   where c0 = pol angle (radians) at reffreq
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.exceptions import ComputationError
from ms_inspect.util.casa_context import open_table, validate_ms_path
from ms_inspect.util.conversions import mjd_seconds_to_unix
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_inspect.util.polcal_setjy_fit import SetjyPolParams, fit_from_catalogue

TOOL_NAME = "ms_setjy_polcal"


def _read_band_range_ghz(ms_str: str) -> tuple[float, float]:
    """Return (lo, hi) GHz spanning all channels of all spectral windows.

    setjy spix/polindex/polangle are per-band local expansions, so the fits must
    be restricted to the observed band — not the catalogue's full 1–48 GHz span.
    """
    import numpy as np

    los: list[float] = []
    his: list[float] = []
    with open_table(ms_str + "/SPECTRAL_WINDOW") as tb:
        for i in range(tb.nrows()):
            cf = tb.getcell("CHAN_FREQ", i)
            los.append(float(np.min(cf)))
            his.append(float(np.max(cf)))
    return min(los) / 1e9, max(his) / 1e9


def _read_obs_year(ms_str: str) -> float | None:
    """Return the decimal observation year from OBSERVATION.TIME_RANGE, or None."""
    from datetime import datetime, timezone

    try:
        with open_table(ms_str + "/OBSERVATION") as tb:
            tr = tb.getcell("TIME_RANGE", 0)  # MJD seconds [start, end]
        mid_unix = mjd_seconds_to_unix((float(tr[0]) + float(tr[1])) / 2.0)
        dt = datetime.fromtimestamp(mid_unix, tz=timezone.utc)
        y0 = datetime(dt.year, 1, 1, tzinfo=timezone.utc)
        y1 = datetime(dt.year + 1, 1, 1, tzinfo=timezone.utc)
        return dt.year + (dt - y0).total_seconds() / (y1 - y0).total_seconds()
    except Exception:
        return None


def _build_script(ms_str: str, field: str, params: SetjyPolParams) -> str:
    """Return a self-contained CASA setjy script for polarization model setting."""
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_setjy_polcal (ms_modify).
Run with: python setjy_polcal.py

Calibrator: {field}
Reference frequency: {params.reffreq_ghz} GHz
Stokes I at reffreq: {params.flux_jy:.4f} Jy
polindex (frac pol at reffreq): {params.polindex[0]:.4f}
polangle (PA at reffreq, rad):  {params.polangle[0]:.4f}
\"\"\"
from casatasks import setjy

ms_path = {ms_str!r}

setjy(
    vis=ms_path,
    field={field!r},
    standard='manual',
    fluxdensity=[{params.flux_jy:.6f}, 0, 0, 0],
    spix={params.spix!r},
    reffreq={params.reffreq_ghz!r},
    polindex={params.polindex!r},
    polangle={params.polangle!r},
    scalebychan=True,
    usescratch=True,
)
print("setjy polcal complete.")
"""


def run(
    ms_path: str,
    field: str,
    workdir: str,
    reffreq_ghz: float,
    calibrator_name: str | None = None,
    epoch: str | None = None,
    pol_freq_range_lo_ghz: float | None = None,
    pol_freq_range_hi_ghz: float | None = None,
    polindex_deg: int = 3,
    polangle_deg: int = 4,
    execute: bool = False,
) -> dict:
    """
    Set the full polarization model for a polarization angle calibrator.

    Args:
        ms_path:              Path to the Measurement Set.
        field:                CASA field selection string (e.g. '3C48').
        workdir:              Existing directory to write setjy_polcal.py into.
        reffreq_ghz:          Reference frequency (GHz) for the polynomial expansion.
        calibrator_name:      Catalogue name to look up (defaults to field if None).
        epoch:                Catalogue epoch key. Default None auto-selects the
                              epoch nearest the observation date (latest if no
                              obs date is supplied).
        pol_freq_range_lo_ghz: Lower bound (GHz) to restrict pol fits.
        pol_freq_range_hi_ghz: Upper bound (GHz) to restrict pol fits.
        polindex_deg:         Degree of polindex polynomial (default 3).
        polangle_deg:         Degree of polangle polynomial (default 4).
        execute:              If False (default), write script only.
                              If True, run setjy in-process.

    Returns:
        Standard response envelope with script_path, calibrator, reffreq_ghz,
        flux_jy, polindex_c0, polangle_c0_rad, and coefficient arrays.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    lookup_name = calibrator_name or field

    # Restrict all fits to the observed band (spix/polindex/polangle are per-band
    # local expansions about reffreq, not global wideband fits).
    try:
        band_lo, band_hi = _read_band_range_ghz(ms_str)
        casa_calls.append("tb.open(SPECTRAL_WINDOW) → CHAN_FREQ (band range)")
    except Exception as exc:
        band_lo = band_hi = None
        warnings.append(
            f"Could not read spectral window band range ({exc}); "
            "fits will use the full catalogue range (NOT per-band)."
        )

    flux_freq_range = (band_lo, band_hi) if band_lo is not None else None

    # Explicit caller override for the pol fits; otherwise default to the band.
    if pol_freq_range_lo_ghz is not None and pol_freq_range_hi_ghz is not None:
        pol_freq_range: tuple[float, float] | None = (pol_freq_range_lo_ghz, pol_freq_range_hi_ghz)
    else:
        pol_freq_range = flux_freq_range

    if band_lo is not None and not (band_lo <= reffreq_ghz <= band_hi):
        warnings.append(
            f"reffreq {reffreq_ghz} GHz is outside the observed band "
            f"({band_lo:.3f}–{band_hi:.3f} GHz); spix is extrapolated."
        )

    obs_year = _read_obs_year(ms_str)
    if obs_year is not None:
        casa_calls.append("tb.open(OBSERVATION) → TIME_RANGE (obs epoch)")

    try:
        params = fit_from_catalogue(
            lookup_name,
            reffreq_ghz=reffreq_ghz,
            epoch=epoch,
            flux_freq_range_ghz=flux_freq_range,
            pol_freq_range_ghz=pol_freq_range,
            polindex_deg=polindex_deg,
            polangle_deg=polangle_deg,
            obs_epoch_year=obs_year,
        )
    except KeyError as exc:
        raise ComputationError(
            f"Calibrator lookup failed: {exc}",
            ms_path=ms_path,
        ) from exc
    except ValueError as exc:
        raise ComputationError(
            f"Polynomial fitting failed: {exc}",
            ms_path=ms_path,
        ) from exc

    script_path = str(workdir_path / "setjy_polcal.py")
    script_content = _build_script(ms_str, field, params)
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "script_path": fmt_field(script_path),
        "calibrator": fmt_field(lookup_name),
        "epoch": epoch,
        "reffreq_ghz": params.reffreq_ghz,
        "flux_jy": fmt_field(round(params.flux_jy, 4)),
        "spix": fmt_field(params.spix),
        "polindex": fmt_field(params.polindex),
        "polindex_c0": round(params.polindex[0], 6),
        "polangle": fmt_field(params.polangle),
        "polangle_c0_rad": round(params.polangle[0], 6),
    }

    if not execute:
        warnings.append(
            f"Script written to {script_path}. Run it externally with CASA to set the model."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run setjy in-process
    try:
        from casatasks import setjy  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.setjy(field='{field}', standard='manual', reffreq={reffreq_ghz}GHz)"
    )
    setjy(
        vis=ms_str,
        field=field,
        standard="manual",
        fluxdensity=[params.flux_jy, 0, 0, 0],
        spix=params.spix,
        reffreq=str(params.reffreq_ghz),
        polindex=params.polindex,
        polangle=params.polangle,
        scalebychan=True,
        usescratch=True,
    )
    base_data["executed"] = True
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
