"""
setjy.py — ms_setjy

Sets flux density models for standard VLA calibrators found in the MS,
using the Perley-Butler 2017 flux standard.

Logic:
  1. Read field names from the MS.
  2. Cross-match against the bundled calibrator catalogue.
  3. For each flux standard found, write setjy() call to script.
  4. Warn if 3C84 (resolved), 3C138, or 3C48 (variable/partially polarized).

Does NOT set polarization angle models (see CALPOL.md).
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.calibrators import lookup
from ms_inspect.util.casa_context import open_table, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope

TOOL_NAME = "ms_setjy"

# Calibrators requiring special treatment
_RESOLVED_WARN = {"3C84", "3C286", "3C147", "3C48"}  # may be resolved
_VARIABLE_WARN = {"3C84", "3C138", "3C48"}  # variable or partially pol
_DEFAULT_STANDARD = "Perley-Butler 2017"


def _get_field_names(ms_str: str) -> list[str]:
    """Read field names from the FIELD subtable."""
    with open_table(ms_str + "/FIELD") as tb:
        return list(tb.getcol("NAME"))


def _build_setjy_block(field_name: str, standard: str) -> str:
    """Return a single setjy() call string for the script."""
    return (
        f"setjy(\n"
        f"    vis=ms_path,\n"
        f"    field={field_name!r},\n"
        f"    standard={standard!r},\n"
        f"    usescratch=False,\n"
        f")"
    )


def _build_script(
    ms_str: str,
    flux_fields: list[str],
    standard: str,
    warnings_inline: list[str],
) -> str:
    """Return a self-contained setjy Python script."""
    warn_block = ""
    if warnings_inline:
        warn_lines = "\n".join(f"# WARNING: {w}" for w in warnings_inline)
        warn_block = warn_lines + "\n\n"

    setjy_blocks = "\n\n".join(_build_setjy_block(f, standard) for f in flux_fields)

    no_flux_block = ""
    if not flux_fields:
        no_flux_block = (
            "# No flux standard fields found in the bundled catalogue.\n"
            "# Verify field names and re-generate this script if needed.\n"
        )

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_setjy (ms_modify).
Run with: python setjy.py
\"\"\"
from casatasks import setjy

ms_path = {ms_str!r}

{warn_block}{no_flux_block}{setjy_blocks}
print("setjy complete.")
"""


def run(
    ms_path: str,
    workdir: str,
    standard: str = _DEFAULT_STANDARD,
    execute: bool = False,
) -> dict:
    """
    Set flux density models for standard calibrators in the MS.

    Args:
        ms_path:  Path to calibrators.ms (or full MS).
        workdir:  Existing output directory for setjy.py script.
        standard: Flux standard (default 'Perley-Butler 2017').
        execute:  If False (default), write setjy.py and return.
                  If True, run setjy in-process for each flux field.

    Returns:
        Standard response envelope with flux_fields, skipped_fields,
        warnings (3C84/3C138/3C48 advisory), and script_path.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    # Read field names from MS
    try:
        field_names = _get_field_names(ms_str)
        casa_calls.append("tb.open(FIELD) → getcol(NAME)")
    except Exception as exc:
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"Could not read FIELD subtable: {exc}",
            ms_path=ms_path,
        ) from exc

    # Cross-match against catalogue — only keep flux calibrators
    flux_fields: list[str] = []
    skipped_fields: list[str] = []
    inline_warnings: list[str] = []

    for fname in field_names:
        entry = lookup(fname)
        if entry is not None and "flux" in entry.role:
            flux_fields.append(fname)
            # Advisory warnings for specific sources
            if entry.canonical_name in _VARIABLE_WARN:
                msg = (
                    f"{fname} ({entry.canonical_name}) is variable or partially "
                    "polarized at frequencies below 4 GHz. Verify flux model validity "
                    "for your band before using these solutions."
                )
                warnings.append(msg)
                inline_warnings.append(msg)
            if entry.resolved:
                msg = (
                    f"{fname} ({entry.canonical_name}) is resolved on long baselines. "
                    "If your array has baselines > safe UV limit, use a component model "
                    "instead of a point-source model."
                )
                warnings.append(msg)
                inline_warnings.append(msg)
        else:
            skipped_fields.append(fname)

    script_path = str(workdir_path / "setjy.py")
    script_content = _build_script(ms_str, flux_fields, standard, inline_warnings)
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "script_path": fmt_field(script_path),
        "flux_fields": fmt_field(flux_fields),
        "skipped_fields": fmt_field(skipped_fields),
        "standard": standard,
        "n_flux_fields": len(flux_fields),
    }

    if not execute:
        if not flux_fields:
            warnings.append(
                "No flux standard fields found in the bundled catalogue. "
                "Check field names match catalogue entries (e.g. '3C286', '3C147')."
            )
        else:
            warnings.append(
                f"Script written to {script_path}. Run it externally to set flux models."
            )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run setjy in-process
    try:
        from casatasks import setjy  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    fields_done: list[str] = []
    for fname in flux_fields:
        casa_calls.append(f"casatasks.setjy(field='{fname}', standard='{standard}')")
        try:
            setjy(
                vis=ms_str,
                field=fname,
                standard=standard,
                usescratch=False,
            )
            fields_done.append(fname)
        except Exception as exc:
            warnings.append(f"setjy(field='{fname}') failed: {exc}")

    base_data["fields_done"] = fmt_field(fields_done)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
