"""
setjy.py — ms_setjy

Sets flux density models for standard VLA calibrators found in the MS,
using the Perley-Butler 2017 flux standard.

Logic:
  1. Read field names from the MS.
  2. Cross-match against the bundled calibrator catalogue.
  3. For each flux standard found, write setjy() call to script.
  4. Warn if 3C84 (resolved), 3C138, or 3C48 (variable/partially polarized).

Does NOT set polarization angle models (see CALPOL.md).
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.calibrators import lookup
from ms_inspect.util.casa_context import open_table, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_inspect.util.stage_log import record_stage

TOOL_NAME = "ms_setjy"

# Calibrators requiring special treatment
_RESOLVED_WARN = {"3C84", "3C286", "3C147", "3C48"}  # may be resolved
_VARIABLE_WARN = {"3C84", "3C138", "3C48"}  # variable or partially pol
_DEFAULT_STANDARD = "Perley-Butler 2017"


def _get_field_names(ms_str: str) -> list[str]:
    """Read field names from the FIELD subtable."""
    with open_table(ms_str + "/FIELD") as tb:
        # Coerce numpy str_ to plain str: repr(np.str_(...)) renders as
        # "np.str_('...')" under numpy >= 2, which is a NameError in the
        # generated script (no numpy import there).
        return [str(n) for n in tb.getcol("NAME")]


def _build_setjy_block(field_name: str, standard: str, usescratch: bool) -> str:
    """Return a single setjy() call string for the script."""
    return (
        f"setjy(\n"
        f"    vis=ms_path,\n"
        f"    field={field_name!r},\n"
        f"    standard={standard!r},\n"
        f"    usescratch={usescratch},\n"
        f")"
    )


def _build_script(
    ms_str: str,
    workdir: str,
    flux_fields: list[str],
    standard: str,
    usescratch: bool,
    warnings_inline: list[str],
) -> str:
    """Return a self-contained setjy Python script."""
    from ms_inspect.util.stage_log import RECORD_STAGE_SNIPPET as record
    from ms_inspect.util.stage_log import TABLE_PROBE_SNIPPET as probe

    warn_block = ""
    if warnings_inline:
        warn_lines = "\n".join(f"# WARNING: {w}" for w in warnings_inline)
        warn_block = warn_lines + "\n\n"

    setjy_blocks = "\n\n".join(_build_setjy_block(f, standard, usescratch) for f in flux_fields)

    no_flux_block = ""
    if not flux_fields:
        no_flux_block = (
            "# No flux standard fields found in the bundled catalogue.\n"
            "# Verify field names and re-generate this script if needed.\n"
        )

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_setjy (ms_modify).
Run with: python setjy.py
\"\"\"
from casatasks import setjy

{record}
{probe}

ms_path = {ms_str!r}

{warn_block}{no_flux_block}{setjy_blocks}
# setjy's job is to put a source model where the solvers can find it. With
# usescratch=True that is a physical MODEL_DATA column; measure it rather than
# assume the call worked.
_model = "MODEL_DATA" in _table_colnames(ms_path)
_record_stage({workdir!r}, "setjy", ms_path, {{"model_data": _model, "usescratch": {usescratch!r}}})
print("setjy complete.")
"""


def run(
    ms_path: str,
    workdir: str,
    standard: str = _DEFAULT_STANDARD,
    usescratch: bool = True,
    exclude_fields: str = "",
    execute: bool = False,
) -> dict:
    """
    Set flux density models for standard calibrators in the MS.

    Args:
        ms_path:    Path to calibrators.ms (or full MS).
        workdir:    Existing output directory for setjy.py script.
        standard:   Flux standard (default 'Perley-Butler 2017').
        exclude_fields: Comma-separated field NAMES to omit from the Stokes-I
                    setjy pass, even if they are catalogued flux standards. Pass
                    the pol-angle calibrator here when it overlaps a flux/BP cal:
                    its full polarized model is set by ms_setjy_polcal
                    (usescratch=True), and a plain Stokes-I setjy on that field
                    would overwrite the polarization (MODEL is last-writer-wins
                    per field). Excluded fields still get a consistent physical
                    MODEL_DATA from ms_setjy_polcal, so usescratch consistency
                    is preserved.
        usescratch: If True (default), fill the physical MODEL_DATA column (so
                    ms_residual_stats and polarization calibration work). If
                    False, write a virtual model (no MODEL_DATA column).
                    Must be consistent across ALL setjy calls on one MS: if
                    polarization calibration is in scope, ms_setjy_polcal forces
                    usescratch=True (virtual models fail on source models with
                    non-zero RM — a known CASA bug), so the flux/bandpass cals
                    must use usescratch=True here too. Mixing the two leaves the
                    virtual-model fields at MODEL_DATA=1 Jy and corrupts the
                    flux scale (fluxscale comes out order-of-magnitude low).
        execute:    If False (default), write setjy.py and return.
                    If True, run setjy in-process for each flux field.

    Returns:
        Standard response envelope with flux_fields, skipped_fields,
        warnings (3C84/3C138/3C48 advisory), and script_path.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    # Read field names from MS
    try:
        field_names = _get_field_names(ms_str)
        casa_calls.append("tb.open(FIELD) → getcol(NAME)")
    except Exception as exc:
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"Could not read FIELD subtable: {exc}",
            ms_path=ms_path,
        ) from exc

    # Cross-match against catalogue — only keep flux calibrators
    flux_fields: list[str] = []
    skipped_fields: list[str] = []
    excluded_fields: list[str] = []
    inline_warnings: list[str] = []

    exclude_set = {n.strip() for n in exclude_fields.split(",") if n.strip()}

    for fname in field_names:
        entry = lookup(fname)
        if fname in exclude_set:
            # Caller-requested skip: the field's model is set elsewhere
            # (ms_setjy_polcal). Do not write a Stokes-I model over it.
            excluded_fields.append(fname)
            continue
        if entry is not None and "flux" in entry.role:
            flux_fields.append(fname)
            # Advisory warnings for specific sources
            if entry.canonical_name in _VARIABLE_WARN:
                msg = (
                    f"{fname} ({entry.canonical_name}) is variable or partially "
                    "polarized at frequencies below 4 GHz. Verify flux model validity "
                    "for your band before using these solutions."
                )
                warnings.append(msg)
                inline_warnings.append(msg)
            if entry.resolved:
                msg = (
                    f"{fname} ({entry.canonical_name}) is resolved on long baselines. "
                    "If your array has baselines > safe UV limit, use a component model "
                    "instead of a point-source model."
                )
                warnings.append(msg)
                inline_warnings.append(msg)
        else:
            skipped_fields.append(fname)

    script_path = str(workdir_path / "setjy.py")
    script_content = _build_script(
        ms_str, str(workdir_path), flux_fields, standard, usescratch, inline_warnings
    )
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "script_path": fmt_field(script_path),
        "flux_fields": fmt_field(flux_fields),
        "skipped_fields": fmt_field(skipped_fields),
        "excluded_fields": fmt_field(excluded_fields),
        "standard": standard,
        "usescratch": usescratch,
        "n_flux_fields": len(flux_fields),
    }

    # Warn if a requested exclusion name never appeared in the MS (likely a typo).
    unmatched_excludes = sorted(exclude_set - set(excluded_fields))
    if unmatched_excludes:
        warnings.append(
            f"exclude_fields names not found in the MS FIELD table: {unmatched_excludes}. "
            "Check the spelling against ms_field_list."
        )

    if not execute:
        if not flux_fields:
            warnings.append(
                "No flux standard fields found in the bundled catalogue. "
                "Check field names match catalogue entries (e.g. '3C286', '3C147')."
            )
        else:
            warnings.append(
                f"Script written to {script_path}. Run it externally to set flux models."
            )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run setjy in-process
    try:
        from casatasks import setjy  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    fields_done: list[str] = []
    for fname in flux_fields:
        casa_calls.append(
            f"casatasks.setjy(field='{fname}', standard='{standard}', usescratch={usescratch})"
        )
        try:
            setjy(
                vis=ms_str,
                field=fname,
                standard=standard,
                usescratch=usescratch,
            )
            fields_done.append(fname)
        except Exception as exc:
            warnings.append(f"setjy(field='{fname}') failed: {exc}")

    # Measure the column rather than infer it from "setjy did not raise".
    # A per-field failure above is a warning, so fields_done can be short while
    # MODEL_DATA is present from an earlier field; the log records both.
    with open_table(ms_str) as tb:
        model_present = "MODEL_DATA" in set(tb.colnames())
    record_stage(
        str(workdir_path),
        "setjy",
        ms_str,
        {
            "model_data": model_present,
            "usescratch": usescratch,
            "n_fields_done": len(fields_done),
        },
    )

    base_data["fields_done"] = fmt_field(fields_done)
    base_data["model_data_present"] = fmt_field(model_present)
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
