"""
setjy_polcal.py — ms_setjy_polcal

Sets the full polarization model (Stokes I + polindex + polangle) for a
polarization angle calibrator using setjy(standard='manual').

Logic:
  1. Look up the calibrator in the pol_calibrators catalogue.
  2. Fit polynomial coefficients via fit_from_catalogue.
  3. Write a setjy(standard='manual') CASA script to workdir/setjy_polcal.py.
  4. Optionally run setjy in-process when execute=True.

CASA coefficient convention (ascending order):
  polindex = [c0, c1, c2, ...]   where c0 = fractional pol at reffreq
  polangle = [c0, c1, c2, ...]   where c0 = pol angle (radians) at reffreq
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.exceptions import ComputationError
from ms_inspect.util.casa_context import validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import response_envelope
from ms_inspect.util.polcal_setjy_fit import SetjyPolParams, fit_from_catalogue

TOOL_NAME = "ms_setjy_polcal"


def _build_script(ms_str: str, field: str, params: SetjyPolParams) -> str:
    """Return a self-contained CASA setjy script for polarization model setting."""
    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_setjy_polcal (ms_modify).
Run with: python setjy_polcal.py

Calibrator: {field}
Reference frequency: {params.reffreq_ghz} GHz
Stokes I at reffreq: {params.flux_jy:.4f} Jy
polindex (frac pol at reffreq): {params.polindex[0]:.4f}
polangle (PA at reffreq, rad):  {params.polangle[0]:.4f}
\"\"\"
from casatasks import setjy

ms_path = {ms_str!r}

setjy(
    vis=ms_path,
    field={field!r},
    standard='manual',
    fluxdensity=[{params.flux_jy:.6f}, 0, 0, 0],
    spix={params.spix!r},
    reffreq={params.reffreq_ghz!r},
    polindex={params.polindex!r},
    polangle={params.polangle!r},
    scalebychan=True,
    usescratch=True,
)
print("setjy polcal complete.")
"""


def run(
    ms_path: str,
    field: str,
    workdir: str,
    reffreq_ghz: float,
    calibrator_name: str | None = None,
    epoch: str = "perley_butler_2013",
    pol_freq_range_lo_ghz: float | None = None,
    pol_freq_range_hi_ghz: float | None = None,
    polindex_deg: int = 3,
    polangle_deg: int = 4,
    execute: bool = False,
) -> dict:
    """
    Set the full polarization model for a polarization angle calibrator.

    Args:
        ms_path:              Path to the Measurement Set.
        field:                CASA field selection string (e.g. '3C48').
        workdir:              Existing directory to write setjy_polcal.py into.
        reffreq_ghz:          Reference frequency (GHz) for the polynomial expansion.
        calibrator_name:      Catalogue name to look up (defaults to field if None).
        epoch:                Catalogue epoch key (default 'perley_butler_2013').
        pol_freq_range_lo_ghz: Lower bound (GHz) to restrict pol fits.
        pol_freq_range_hi_ghz: Upper bound (GHz) to restrict pol fits.
        polindex_deg:         Degree of polindex polynomial (default 3).
        polangle_deg:         Degree of polangle polynomial (default 4).
        execute:              If False (default), write script only.
                              If True, run setjy in-process.

    Returns:
        Standard response envelope with script_path, calibrator, reffreq_ghz,
        flux_jy, polindex_c0, polangle_c0_rad, and coefficient arrays.
    """
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    casa_calls: list[str] = []
    warnings: list[str] = []

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        raise ComputationError(
            f"workdir does not exist: {workdir}. Create it before calling this tool.",
            ms_path=ms_path,
        )

    lookup_name = calibrator_name or field
    pol_freq_range = (
        (pol_freq_range_lo_ghz, pol_freq_range_hi_ghz)
        if pol_freq_range_lo_ghz is not None and pol_freq_range_hi_ghz is not None
        else None
    )

    try:
        params = fit_from_catalogue(
            lookup_name,
            reffreq_ghz=reffreq_ghz,
            epoch=epoch,
            pol_freq_range_ghz=pol_freq_range,
            polindex_deg=polindex_deg,
            polangle_deg=polangle_deg,
        )
    except KeyError as exc:
        raise ComputationError(
            f"Calibrator lookup failed: {exc}",
            ms_path=ms_path,
        ) from exc
    except ValueError as exc:
        raise ComputationError(
            f"Polynomial fitting failed: {exc}",
            ms_path=ms_path,
        ) from exc

    script_path = str(workdir_path / "setjy_polcal.py")
    script_content = _build_script(ms_str, field, params)
    Path(script_path).write_text(script_content)
    casa_calls.append(f"write_script → {script_path}")

    base_data: dict = {
        "script_path": fmt_field(script_path),
        "calibrator": fmt_field(lookup_name),
        "epoch": epoch,
        "reffreq_ghz": params.reffreq_ghz,
        "flux_jy": fmt_field(round(params.flux_jy, 4)),
        "spix": fmt_field(params.spix),
        "polindex": fmt_field(params.polindex),
        "polindex_c0": round(params.polindex[0], 6),
        "polangle": fmt_field(params.polangle),
        "polangle_c0_rad": round(params.polangle[0], 6),
    }

    if not execute:
        warnings.append(
            f"Script written to {script_path}. Run it externally with CASA to set the model."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=base_data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run setjy in-process
    try:
        from casatasks import setjy  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed or cannot be imported.",
            ms_path=ms_path,
        ) from None

    casa_calls.append(
        f"casatasks.setjy(field='{field}', standard='manual', reffreq={reffreq_ghz}GHz)"
    )
    setjy(
        vis=ms_str,
        field=field,
        standard="manual",
        fluxdensity=[params.flux_jy, 0, 0, 0],
        spix=params.spix,
        reffreq=str(params.reffreq_ghz),
        polindex=params.polindex,
        polangle=params.polangle,
        scalebychan=True,
        usescratch=True,
    )
    base_data["executed"] = True
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=base_data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
