"""
tclean.py — ms_tclean

Generate a first-pass imaging script using CASA tclean.

All imaging parameters are accepted explicitly — no parameter derivation
is done inside this tool. See skill 11-imaging.md for derivation logic.

When execute=False (default), writes a self-contained script to
workdir/tclean_<imagename_stem>.py and returns immediately. Run it
externally as a background job; tclean on a real mosaic can take hours.
"""

from __future__ import annotations

from pathlib import Path

from ms_inspect.util.casa_context import open_table, validate_ms_path
from ms_inspect.util.formatting import field as fmt_field
from ms_inspect.util.formatting import normalize_field_sel, response_envelope
from ms_modify.exceptions import TcleanFailedError

TOOL_NAME = "ms_tclean"


def _script_path(workdir: Path, imagename: str) -> Path:
    stem = Path(imagename).name.replace(".", "_")
    return workdir / f"tclean_{stem}.py"


def _build_script(
    ms_str: str,
    imagename: str,
    field: str,
    stokes: str,
    specmode: str,
    deconvolver: str,
    nterms: int | None,
    gridder: str,
    wprojplanes: int | None,
    cell: str,
    imsize: list[int],
    weighting: str,
    robust: float,
    niter: int,
    threshold: str,
    savemodel: str,
) -> str:
    optional_lines = ""
    if deconvolver == "mtmfs" and nterms is not None:
        optional_lines += f"    nterms       = {nterms},\n"
    if wprojplanes is not None:
        optional_lines += f"    wprojplanes  = {wprojplanes},\n"

    script_name = Path(imagename).name.replace(".", "_")

    return f"""\
#!/usr/bin/env python
\"\"\"
Auto-generated by ms_tclean (ms_modify).
Run with: python tclean_{script_name}.py
\"\"\"
import glob
import os
import shutil
from casatasks import tclean

ms_path   = {ms_str!r}
imagename = {imagename!r}

# Remove all existing image products for this imagename before re-running.
for p in glob.glob(imagename + ".*"):
    if os.path.isdir(p):
        shutil.rmtree(p)
    elif os.path.isfile(p):
        os.remove(p)

tclean(
    vis          = ms_path,
    imagename    = imagename,
    field        = {field!r},
    stokes       = {stokes!r},
    specmode     = {specmode!r},
    deconvolver  = {deconvolver!r},
{optional_lines}    gridder      = {gridder!r},
    cell         = [{cell!r}],
    imsize       = {imsize!r},
    weighting    = {weighting!r},
    robust       = {robust},
    niter        = {niter},
    threshold    = {threshold!r},
    pbcor        = True,
    savemodel    = {savemodel!r},
)
print("tclean complete. Images written with base name:", imagename)
"""


def run(
    ms_path: str,
    imagename: str,
    field: str,
    workdir: str,
    stokes: str = "I",
    specmode: str = "mfs",
    deconvolver: str = "hogbom",
    nterms: int | None = None,
    gridder: str = "standard",
    wprojplanes: int | None = None,
    cell: str = "1.0arcsec",
    imsize: list[int] | None = None,
    weighting: str = "briggs",
    robust: float = 0.5,
    niter: int = 50000,
    threshold: str = "1.0mJy",
    savemodel: str = "modelcolumn",
    execute: bool = False,
) -> dict:
    """
    Generate (and optionally execute) a tclean imaging script.

    Validates that CORRECTED_DATA exists in the MS before writing the script.
    pbcor=True is always set — primary beam correction is applied by tclean.

    Args:
        ms_path:     Path to the full Measurement Set.
        imagename:   Base name for all output image products (no suffix).
        field:       CASA field selection for science target(s).
        workdir:     Existing directory for script and image output.
        stokes:      Stokes products to image (default 'I').
        specmode:    'mfs' or 'cube' (default 'mfs').
        deconvolver: 'hogbom' or 'mtmfs' (default 'hogbom').
        nterms:      Taylor terms for mtmfs (default None; pass 2 for mtmfs).
        gridder:     'standard', 'wproject', or 'awp2' (default 'standard').
        wprojplanes: W-projection planes (None = omit; set for wproject/awp2
                     when W-terms are required per Fresnel criterion).
        cell:        Cell size string, e.g. '2.5arcsec'.
        imsize:      Image size as [nx, ny] (default [512, 512]).
        weighting:   UV weighting scheme (default 'briggs').
        robust:      Briggs robust parameter (default 0.5).
        niter:       Maximum clean iterations (default 50000).
        threshold:   Clean stopping threshold, e.g. '0.5mJy'.
        savemodel:   'modelcolumn' writes MODEL_DATA for self-cal (default).
        execute:     If False (default), write script and return.
                     If True, run tclean in-process (intended for test data only).

    Returns:
        Standard response envelope with script_path always present.
        When execute=True, also includes imagename and completed flag.
    """
    field = normalize_field_sel(field)
    p = validate_ms_path(ms_path)
    ms_str = str(p)
    warnings: list[str] = []
    casa_calls: list[str] = []

    if imsize is None:
        imsize = [512, 512]

    workdir_path = Path(workdir)
    if not workdir_path.exists():
        from ms_inspect.exceptions import ComputationError

        raise ComputationError(
            f"workdir does not exist: {workdir}",
            ms_path=ms_path,
        )

    # Verify CORRECTED_DATA column exists.
    # Open failure (casatools not installed, table locked) is non-fatal — add a warning.
    # Missing column is always fatal — tclean on uncalibrated data is a silent science error.
    col_names: list[str] = []
    try:
        with open_table(ms_str) as tb:
            col_names = list(tb.colnames())
        casa_calls.append("tb.open(MS) → colnames() [CORRECTED_DATA check]")
    except Exception as exc:
        warnings.append(f"Could not verify CORRECTED_DATA column: {exc}")

    if col_names and "CORRECTED_DATA" not in col_names:
        from ms_inspect.exceptions import InsufficientMetadataError

        raise InsufficientMetadataError(
            "CORRECTED_DATA column not found in MS. Run ms_applycal before imaging.",
            ms_path=ms_path,
        )

    script_file = _script_path(workdir_path, imagename)
    script_content = _build_script(
        ms_str=ms_str,
        imagename=imagename,
        field=field,
        stokes=stokes,
        specmode=specmode,
        deconvolver=deconvolver,
        nterms=nterms,
        gridder=gridder,
        wprojplanes=wprojplanes,
        cell=cell,
        imsize=imsize,
        weighting=weighting,
        robust=robust,
        niter=niter,
        threshold=threshold,
        savemodel=savemodel,
    )
    script_file.write_text(script_content)
    casa_calls.append(f"write_script → {script_file}")

    if not execute:
        data = {
            "script_path": fmt_field(str(script_file)),
            "imagename": fmt_field(imagename),
            "completed": fmt_field(False, note="script not yet executed"),
        }
        warnings.append(
            f"Script written to {script_file}. Run it externally as a background job; "
            "tclean on real data can take hours."
        )
        return response_envelope(
            tool_name=TOOL_NAME,
            ms_path=ms_path,
            data=data,
            warnings=warnings,
            casa_calls=casa_calls,
        )

    # execute=True: run tclean in-process.
    try:
        from casatasks import tclean as _tclean  # type: ignore[import]
    except ImportError:
        from ms_inspect.exceptions import CASANotAvailableError

        raise CASANotAvailableError(
            "casatasks is not installed.",
            ms_path=ms_path,
        ) from None

    tclean_kwargs: dict = dict(
        vis=ms_str,
        imagename=imagename,
        field=field,
        stokes=stokes,
        specmode=specmode,
        deconvolver=deconvolver,
        gridder=gridder,
        cell=[cell],
        imsize=imsize,
        weighting=weighting,
        robust=robust,
        niter=niter,
        threshold=threshold,
        pbcor=True,
        savemodel=savemodel,
    )
    if deconvolver == "mtmfs" and nterms is not None:
        tclean_kwargs["nterms"] = nterms
    if wprojplanes is not None:
        tclean_kwargs["wprojplanes"] = wprojplanes

    casa_calls.append(f"casatasks.tclean(imagename={imagename!r}, ...)")
    try:
        _tclean(**tclean_kwargs)
    except Exception as exc:
        raise TcleanFailedError(
            f"tclean raised: {exc}",
            ms_path=ms_path,
        ) from exc

    image_path = imagename + ".image"
    completed = Path(image_path).exists()
    if not completed:
        raise TcleanFailedError(
            f"tclean completed without error but {image_path} was not created.",
            ms_path=ms_path,
        )

    data = {
        "script_path": fmt_field(str(script_file)),
        "imagename": fmt_field(imagename),
        "completed": fmt_field(completed),
    }
    return response_envelope(
        tool_name=TOOL_NAME,
        ms_path=ms_path,
        data=data,
        warnings=warnings,
        casa_calls=casa_calls,
    )
